apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-basic
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: jenkins-basic-bc
    name: jenkins-basic
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-basic:v1.0.0
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: .jenkins/docker
      git:
        ref: master
        uri: https://github.com/bcgov/tfrs.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: bcgov-jenkins-basic:v2-20200303
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
