apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: Secret
  type: kubernetes.io/basic-auth
  metadata:
    annotations: null
    name: ${NAME}-slave-user
  stringData:
    metadata.name: ${NAME}-slave-user
    password: ${SLAVE_USER_PASSWORD}
    username: jenkins-slave
- apiVersion: v1
  kind: Secret
  type: kubernetes.io/basic-auth
  metadata:
    annotations: null
    name: ${NAME}-github
  stringData:
    metadata.name: ${NAME}-github
    password: ${GITHUB_PASSWORD}
    username: ${GITHUB_USERNAME}
- apiVersion: v1
  kind: Secret
  type: kubernetes.io/basic-auth
  metadata:
    annotations: null
    name: ${NAME}-browserstack
  stringData:
    metadata.name: ${NAME}-browserstack
    accesskey: ${BROWSERSTACK_ACCESSKEY}
    username: ${BROWSERSTACK_USERNAME}
- apiVersion: v1
  kind: Secret
  type: kubernetes.io/basic-auth
  metadata:
    annotations: null
    name: ${NAME}-functional-test-users
  stringData:
    metadata.name: ${NAME}-functional-test-users
    functional_test_users_v2: ${FUNCTIONAL_TEST_USERS}
parameters:
- name: NAME
  description: <-
    This name will be given to all objects so they can be uniquley referenced.
  displayName: Name
  required: true
  value: jenkins
- name: GITHUB_USERNAME
  description: <-
    The name of the GitHub user that Jenkins will use to access the GitHub API
  required: true
- name: GITHUB_PASSWORD
  description: <-
    The Personal Access Token assocated with the GitHub user. This will function as a
    password for the user.
  required: true
- name: SLAVE_USER_PASSWORD
  description: <-
    The password for the Jenkins slave user. This will be updated by the deployment
    so its best to let it be auto-generated for now.
  from: '[a-zA-Z0-9]{16}'
  generate: expression
- name: BROWSERSTACK_USERNAME
  description: <-
    BrowserStack Automatem username.
  required: true
- name: BROWSERSTACK_ACCESSKEY
  description: <-
    BrowserStack Automatem accesskey.
  required: true
- name: FUNCTIONAL_TEST_USERS
  description: <-
    Funtional test users.
  required: true