---
kind: Template
apiVersion: v1
metadata:
  name: "${APP_NAME}"
parameters:
- name: NAME
  displayName: Name
  description: The suffix for all created objects
  required: false
  value: maintenance-page
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: maintenance-page
    creationTimestamp:
    labels:
      app: maintenance-page
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: maintenance-page
    creationTimestamp:
    labels:
      app: maintenance-page
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    runPolicy: SerialLatestOnly
    source:
      type: Git
      contextDir: "/maintenance"
      git:
        uri: https://github.com/bcgov/tfrs.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: caddy-s2i-builder:latest
    output:
      to:
        kind: ImageStreamTag
        name: maintenance-page:latest
    resources: {}
    postCommit: {}
    nodeSelector:
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
