export default {
  ERROR_COMPLIANCE_PERIODS: 'ERROR_COMPLIANCE_PERIODS',
  ERROR_COMPLIANCE_PERIODS_REQUEST: 'ERROR_COMPLIANCE_PERIODS_REQUEST',
  GET_COMPLIANCE_PERIODS: 'GET_COMPLIANCE_PERIODS',
  GET_COMPLIANCE_PERIODS_REQUEST: 'GET_COMPLIANCE_PERIODS_REQUEST',
  RECEIVE_COMPLIANCE_PERIODS: 'RECEIVE_COMPLIANCE_PERIODS',
  RECEIVE_COMPLIANCE_PERIODS_REQUEST: 'RECEIVE_COMPLIANCE_PERIODS_REQUEST'
};
