export default {
  ADD_DOCUMENT_UPLOAD: 'ADD_DOCUMENT_UPLOAD',
  ERROR: 'ERROR',
  GET_REQUEST: 'GET_REQUEST',
  GET_REQUESTS: 'GET_REQUESTS',
  RECEIVE_REQUEST: 'RECEIVE_REQUEST',
  RECEIVE_REQUESTS: 'RECEIVE_REQUESTS',
  REQUEST: 'REQUEST',
  SUCCESS: 'SUCCESS',
  SUCCESS_ADD_DOCUMENT_UPLOAD: 'SUCCESS_ADD_DOCUMENT_UPLOAD',
  SUCCESS_UPDATE_DOCUMENT_UPLOAD: 'SUCCESS_UPDATE_DOCUMENT_UPLOAD',
  UPDATE_DOCUMENT_UPLOAD: 'UPDATE_DOCUMENT_UPLOAD'
};
