export default {
  ADD_DOCUMENT_UPLOAD: 'ADD_DOCUMENT_UPLOAD',
  CLEAR_ERROR: 'CLEAR_ERROR',
  ERROR_GET_UPLOAD_URL: 'ERROR_GET_UPLOAD_URL',
  ERROR: 'ERROR',
  GET_REQUEST: 'GET_REQUEST',
  GET_REQUESTS: 'GET_REQUESTS',
  GET_UPLOAD_URL_REQUEST: 'GET_UPLOAD_URL_REQUEST',
  GET_UPLOAD_URL: 'GET_UPLOAD_URL',
  RECEIVE_REQUEST: 'RECEIVE_REQUEST',
  RECEIVE_REQUESTS: 'RECEIVE_REQUESTS',
  REQUEST: 'REQUEST',
  SUCCESS_ADD_DOCUMENT_UPLOAD: 'SUCCESS_ADD_DOCUMENT_UPLOAD',
  SUCCESS_GET_UPLOAD_URL: 'SUCCESS_GET_UPLOAD_URL',
  SUCCESS_UPDATE_DOCUMENT_UPLOAD: 'SUCCESS_UPDATE_DOCUMENT_UPLOAD',
  SUCCESS: 'SUCCESS',
  UPDATE_DOCUMENT_UPLOAD: 'UPDATE_DOCUMENT_UPLOAD'
};
