export default {
  INIT_KEYCLOAK: 'INIT_KEYCLOAK',
  INIT_KEYCLOAK_ERROR: 'INIT_KEYCLOAK_ERROR',
  LOGIN_KEYCLOAK_USER_SUCCESS: 'LOGIN_KEYCLOAK_USER_SUCCESS',
  LOGIN_KEYCLOAK_USER_ERROR: 'LOGIN_KEYCLOAK_USER_ERROR',
  LOGOUT_KEYCLOAK_USER: 'LOGOUT_KEYCLOAK_USER',
  
  // LOGOUT: 'LOGOUT',
  // USER_EXPIRED: 'USER_EXPIRED',
  // REDIRECT_SUCCESS: 'REDIRECT_SUCCESS',
  // USER_LOADED: 'USER_LOADED',
  // SILENT_RENEW_ERROR: 'SILENT_RENEW_ERROR',
  // SESSION_TERMINATED: 'SESSION_TERMINATED',
  // USER_EXPIRING: 'USER_EXPIRING',
  // USER_FOUND: 'USER_FOUND',
  // LOADING_USER: 'LOADING_USER',
  // LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  // USER_SIGNED_OUT: 'USER_SIGNED_OUT',
};
