export default {
  INIT_KEYCLOAK: 'INIT_KEYCLOAK',
  INIT_KEYCLOAK_ERROR: 'INIT_KEYCLOAK_ERROR',
  LOGGING_IN: 'LOGGING_IN',
  LOGGING_IN_DONE: 'LOGGING_IN_DONE',
  LOGIN_KEYCLOAK_REFRESH_SUCCESS: 'LOGIN_KEYCLOAK_REFRESH_SUCCESS',
  LOGIN_KEYCLOAK_SILENT_REFRESH_SUCCESS: 'LOGIN_KEYCLOAK_SILENT_REFRESH_SUCCESS',
  LOGIN_KEYCLOAK_USER_SUCCESS: 'LOGIN_KEYCLOAK_USER_SUCCESS',
  LOGIN_KEYCLOAK_USER_ERROR: 'LOGIN_KEYCLOAK_USER_ERROR',
  LOGOUT_KEYCLOAK_USER: 'LOGOUT_KEYCLOAK_USER',
  RESET_AUTH: 'RESET_AUTH',
  RESET_TOKEN: 'RESET_TOKEN',
  SESSION_TIMEOUT_CONTINUE: 'SESSION_TIMEOUT_CONTINUE'
}
