export default {
  ERROR: 'ERROR',
  SERVER_INITIATED_NOTIFICATION_RELOAD: 'SERVER_INITIATED_NOTIFICATION_RELOAD',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
  POST_CHANGE_NOTIFICATION_READ_STATUS: 'POST_CHANGE_NOTIFICATION_READ_STATUS',
  RECEIVE_CHANGE_NOTIFICATION_READ_STATUS: 'RECEIVE_CHANGE_NOTIFICATION_READ_STATUS'
  GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
  INVALIDATE_NOTIFICATIONS: 'INVALIDATE_NOTIFICATIONS',
  INVALIDATE_SUBSCRIPTIONS: 'INVALIDATE_SUBSCRIPTIONS',
  RECEIVE_SUBSCRIPTIONS: 'RECEIVE_SUBSCRIPTIONS',
  REQUEST: 'REQUEST',
  SUCCESS: 'SUCCESS'
};
