export default {
  ERROR: 'ERROR',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
  INVALIDATE_NOTIFICATIONS: 'INVALIDATE_NOTIFICATIONS',
  INVALIDATE_SUBSCRIPTIONS: 'INVALIDATE_SUBSCRIPTIONS',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
  RECEIVE_SUBSCRIPTIONS: 'RECEIVE_SUBSCRIPTIONS',
  REQUEST: 'REQUEST',
  SERVER_INITIATED_NOTIFICATION_RELOAD: 'SERVER_INITIATED_NOTIFICATION_RELOAD',
  SUCCESS: 'SUCCESS'
};
