export default {
  ADD_SIGNING_AUTHORITY_CONFIRMATION: 'ADD_SIGNING_AUTHORITY_CONFIRMATION',
  ERROR: 'ERROR',
  SUCCESS_ADD_SIGNING_AUTHORITY_CONFIRMATION: 'SUCCESS_ADD_SIGNING_AUTHORITY_CONFIRMATION'
};
