export default {
  ADD_SIGNING_AUTHORITY_CONFIRMATION: 'ADD_SIGNING_AUTHORITY_CONFIRMATION',
  ERROR_ADD_SIGNING_AUTHORITY_CONFIRMATION: 'ERROR_ADD_SIGNING_AUTHORITY_CONFIRMATION',
  SUCCESS_ADD_SIGNING_AUTHORITY_CONFIRMATION: 'SUCCESS_ADD_SIGNING_AUTHORITY_CONFIRMATION'
};
