const ActionTypes = {
  GET_USER_LOGIN_HISTORY_REQUEST: 'GET_USER_LOGIN_HISTORY_REQUEST',
  GET_USER_LOGIN_HISTORY_SUCCESS: 'GET_USER_LOGIN_HISTORY_SUCCESS',
  GET_USER_LOGIN_HISTORY_FAILURE: 'GET_USER_LOGIN_HISTORY_FAILURE'
}

export default ActionTypes
