# Generated by Django 3.2.19 on 2023-05-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='latest_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_reports', to='api.compliancereport'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='root_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_reports', to='api.compliancereport'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='traversal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='compliance_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.complianceperiod'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.compliancereporttype'),
        ),
        migrations.AlterField(
            model_name='compliancereportsnapshot',
            name='compliance_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliance_report_snapshot', to='api.compliancereport'),
        ),
        migrations.AlterField(
            model_name='credittrade',
            name='documents',
            field=models.ManyToManyField(related_name='credit_trade_documents', through='api.DocumentCreditTrade', to='api.Document'),
        ),
    ]
