# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_organization_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittradestatus',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credittradetype',
            name='the_type',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationactionstype',
            name='the_type',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationstatus',
            name='status',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='type',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
