# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 22:07
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180208_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittrade',
            name='fair_market_value_per_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=999, null=True),
        ),
    ]
