# Generated by Django 3.2.19 on 2023-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_migrate_compliance_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=512, unique=True)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'cached_pages',
            },
        ),
    ]
