# Generated by Django 3.2.19 on 2023-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cachedpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittrade',
            name='date_of_written_agreement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='date_of_written_agreement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
