# Generated by Django 3.2.19 on 2023-07-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230701_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTradeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Reached within the last 6 months'), ('B', 'Reached between 6 months to 1 year ago'), ('C', 'Reached more than 1 year ago'), ('D', 'Override based on value of price per credit')], default='A', max_length=1, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'credit_trade_category',
            },
        ),
        migrations.AddField(
            model_name='credittrade',
            name='trade_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_trades', to='api.credittradecategory'),
        ),
        migrations.AddField(
            model_name='credittrade',
            name='category_d_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='category_d_selected',
            field=models.BooleanField(default=False),
        ),
    ]
