# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180424_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittradehistory',
            name='compliance_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_trade_histories', to='api.CompliancePeriod'),
        ),
    ]
