# Generated by Django 3.2.19 on 2023-08-08 18:24

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_admin_adjustment_20230808_1803'),
    ]

    operations = [
        # Remove the old status field
        migrations.RemoveField(
            model_name='compliancereporthistory',
            name='status'
        ),
        # Add the new ForeignKey status field
        migrations.AddField(
            model_name='compliancereporthistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_report', to='api.compliancereportworkflowstate'),
        ),
    ]
