# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_credittradehistory_compliance_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittrade',
            options={'permissions': (('credit_trade_approve', 'Can approve credit transfers'),)},
        ),
    ]
