# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170731_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelsupplier',
            old_name='dateCreated',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='datePosted',
            new_name='postedDate',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='creditTradeStatusId',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='creditTradeTypeId',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='history',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='creditTradeStatusId',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='creditTradeTypeId',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='credittradetype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fuelsupplier',
            name='fuelSupplierActionsTypeId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplier',
            name='fuelSupplierStatusId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplier',
            name='fuelSupplierTypeId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplieractionstype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierattachment',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierattachmenttag',
            name='fuelSupplierAttachmentId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierbalance',
            name='creditTradeId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierbalance',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierccdata',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliercontact',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliercontact',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliercontactrole',
            name='roleId',
        ),
        migrations.RemoveField(
            model_name='fuelsupplierhistory',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliertype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificationEventId',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='creditTradeId',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='opportunityId',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='creditTradeTypeId',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='creditTrades',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='fuelSupplierTypeId',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='numberOfViews',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='opportunityStatusId',
        ),
        migrations.RemoveField(
            model_name='opportunityhistory',
            name='creditTradeTypeId',
        ),
        migrations.RemoveField(
            model_name='opportunityhistory',
            name='fuelSupplierTypeId',
        ),
        migrations.RemoveField(
            model_name='opportunityhistory',
            name='opportunityId',
        ),
        migrations.RemoveField(
            model_name='opportunityhistory',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permissionId',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='roleId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fuelSupplierId',
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='effectiveDate',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='expiryDate',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='credittrade',
            name='creditTradeStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradecreditTradeStatusFK', to='api.CreditTradeStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittrade',
            name='creditTradeTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradecreditTradeTypeFK', to='api.CreditTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittrade',
            name='historySet',
            field=models.ManyToManyField(blank=True, related_name='CreditTradehistorySet', to='api.CreditTradeHistory'),
        ),
        migrations.AddField(
            model_name='credittrade',
            name='initiatorFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeinitiatorFK', to='api.FuelSupplier'),
        ),
        migrations.AddField(
            model_name='credittrade',
            name='respondentFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTraderespondentFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='creditTradeStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeHistorycreditTradeStatusFK', to='api.CreditTradeStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='creditTradeTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeHistorycreditTradeTypeFK', to='api.CreditTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='newRespondentFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeHistorynewRespondentFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='userFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeHistoryuserFK', to='api.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittradetype',
            name='theType',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='fuelsupplier',
            name='fuelSupplierActionsTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierfuelSupplierActionsTypeFK', to='api.FuelSupplierActionsType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplier',
            name='fuelSupplierStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierfuelSupplierStatusFK', to='api.FuelSupplierStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplier',
            name='fuelSupplierTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierfuelSupplierTypeFK', to='api.FuelSupplierType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplieractionstype',
            name='theType',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplierattachment',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierAttachmentfuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplierattachmenttag',
            name='fuelSupplierAttachmentFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierAttachmentTagfuelSupplierAttachmentFK', to='api.FuelSupplierAttachment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplierbalance',
            name='creditTradeFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierBalancecreditTradeFK', to='api.CreditTrade'),
        ),
        migrations.AddField(
            model_name='fuelsupplierbalance',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierBalancefuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplierccdata',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierCCDatafuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsuppliercontact',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierContactfuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsuppliercontact',
            name='userFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierContactuserFK', to='api.User'),
        ),
        migrations.AddField(
            model_name='fuelsuppliercontactrole',
            name='roleFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierContactRoleroleFK', to='api.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsupplierhistory',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FuelSupplierHistoryfuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelsuppliertype',
            name='theType',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notificationEventFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationnotificationEventFK', to='api.NotificationEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='userFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationuserFK', to='api.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='creditTradeFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationEventcreditTradeFK', to='api.CreditTrade'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='opportunityFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationEventopportunityFK', to='api.Opportunity'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='theType',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='creditTradeTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunitycreditTradeTypeFK', to='api.CreditTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='creditTradesSet',
            field=models.ManyToManyField(blank=True, related_name='OpportunitycreditTradesSet', to='api.CreditTrade'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='fuelSupplierFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityfuelSupplierFK', to='api.FuelSupplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='fuelSupplierTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityfuelSupplierTypeFK', to='api.FuelSupplierType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunityStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityopportunityStatusFK', to='api.OpportunityStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunityhistory',
            name='creditTradeTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityHistorycreditTradeTypeFK', to='api.CreditTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunityhistory',
            name='fuelSupplierTypeFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityHistoryfuelSupplierTypeFK', to='api.FuelSupplierType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunityhistory',
            name='opportunityFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityHistoryopportunityFK', to='api.Opportunity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunityhistory',
            name='userFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityHistoryuserFK', to='api.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permissionFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RolePermissionpermissionFK', to='api.Permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='roleFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RolePermissionroleFK', to='api.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavourite',
            name='userFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserFavouriteuserFK', to='api.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='roleFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserRoleroleFK', to='api.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='userFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserRoleuserFK', to='api.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='appCreateUserDirectory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='appCreateUserGuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='appCreateUserid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='appLastUpdateUserDirectory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='appLastUpdateUserGuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='appLastUpdateUserid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='entityName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='newValue',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='oldValue',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='propertyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credittrade',
            name='plainEnglishPhrase',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='credittradehistory',
            name='note',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='credittradestatus',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='credittradestatus',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='credittradetype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='credittradetype',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplier',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fuelsupplieractionstype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplieractionstype',
            name='effectiveDate',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelsupplierattachment',
            name='complianceYear',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierattachment',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierattachment',
            name='fileLocation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierattachment',
            name='fileName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierattachmenttag',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='commonClientOrgId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='corporateAddressCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='corporateAddressLine1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='corporateAddressLine2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='corporateAddressPostalCode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='corporateAddressProvince',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierccdata',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='givenName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='mobilePhoneNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='notes',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliercontact',
            name='workPhoneNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierhistory',
            name='historyText',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fuelsupplierstatus',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsupplierstatus',
            name='status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelsuppliertype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsuppliertype',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='eventTypeCode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='effectiveDate',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunityBackgroundNote',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='plainEnglishPhrase',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='opportunityhistory',
            name='note',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='opportunitystatus',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opportunitystatus',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='authorizationDirectory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='authorizationID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='givenName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='value',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
