# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180426_2242'),
        ('api', '0007_credittradehistory_compliance_period'),
    ]

    operations = [
    ]
