# Generated by Django 3.2.20 on 2023-10-10 22:21

from django.db import migrations, models

def change_organization_types(apps, schema_editor):
    OrganizationType = apps.get_model('api', 'OrganizationType')

    # Change the type values
    OrganizationType.objects.filter(type="Part3FuelSupplier").update(type="FuelSupplier")
    OrganizationType.objects.filter(type="FuelSupplier").update(description="Fuel Supplier")

    # Add a new type
    OrganizationType.objects.create(type="ElectricitySupplier", description="Electricity Supplier", 
                                    effective_date="2023-01-01", expiration_date='2117-01-01', display_order=3)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230718_0104'),
    ]

    operations = [
        migrations.RunPython(change_organization_types),
        migrations.AddField(
            model_name='organization',
            name='edrms_record',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
