# Generated by Django 3.2.20 on 2023-10-10 22:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230718_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='edrms_record',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
