# Generated by Django 3.2.20 on 2023-08-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230718_0104'),
        ('api', '0009_alter_compliace_report_history_status'),
    ]

    operations = [
    ]
