# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170821_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittrade',
            name='numberOfCredits',
            field=models.IntegerField(validators=[api.validators.CreditTradeNumberOfCreditsValidator]),
        ),
    ]
