# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 18:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180529_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittrade',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in theformat: '+999999999'. Up to 15 digitsallowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in theformat: '+999999999'. Up to 15 digitsallowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
    ]
