# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_credittradecomment_squashed_0014_auto_20180613_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittradecomment',
            name='credit_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_trade_comments', to='api.CreditTrade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in theformat: '+999999999'. Up to 15 digitsallowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in theformat: '+999999999'. Up to 15 digitsallowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
