# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171012_1529'),
    ]

    """
    Since we're just renaming the tables to lowercase, Django isn't smart enough
    to figure out that they're different. So we rename them with a _ suffix 
    before the actual rename
    """
    operations = [

        migrations.AlterModelTable(
            name='credittradezeroreason',
            table='credit_trade_zero_reason_',
        ),
        migrations.AlterModelTable(
            name='credittradezeroreason',
            table='credit_trade_zero_reason',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role_',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permission_',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permission',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userfavourite',
            table='user_favourite_',
        ),
        migrations.AlterModelTable(
            name='userfavourite',
            table='user_favourite',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role_',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
