# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_credittradecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittrade',
            old_name='rescinded',
            new_name='is_rescinded',
        ),
        migrations.RenameField(
            model_name='credittradehistory',
            old_name='rescinded',
            new_name='is_rescinded',
        ),
    ]
