# Generated by Django 3.2.19 on 2023-08-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_admin_adjustment_20230808_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittrade',
            name='number_of_credits',
            field=models.IntegerField(),
        ),
    ]
