# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171013_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsuppliercontactrole',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliercontactrole',
            name='roleFK',
        ),
        migrations.RemoveField(
            model_name='fuelsuppliercontactrole',
            name='update_user',
        ),
        migrations.AddField(
            model_name='credittradehistory',
            name='newCreditTradeZeroReasonFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditTradeHistorynewCreditTradeZeroReasonFK', to='api.CreditTradeZeroReason'),
        ),
        migrations.AddField(
            model_name='role',
            name='isGovernmentRole',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FuelSupplierContactRole',
        ),
    ]
