# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171013_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittradehistory',
            old_name='note',
            new_name='newNote',
        ),
        migrations.AddField(
            model_name='credittrade',
            name='note',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='isGovernmentRole',
            field=models.BooleanField(default=False),
        ),
    ]
