# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180628_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittradecomment',
            name='privileged_access',
            field=models.BooleanField(db_column='is_privileged_access', default=True),
        ),
    ]
