# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180703_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittradecomment',
            name='trade_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_trade_comments', to='api.CreditTradeHistory'),
        ),
    ]
