# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_credittradecomment_trade_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittradecomment',
            old_name='trade_history',
            new_name='trade_history_at_creation',
        ),
    ]
