# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_auto_20171116_1250'),
    ]

    operations = [
        migrations.RenameModel('FuelSupplier', 'Organization'),
        migrations.RenameModel('FuelSupplierActionsType',
                               'OrganizationActionsType'),
        migrations.RenameModel('FuelSupplierAttachment',
                               'OrganizationAttachment'),
        migrations.RenameModel('FuelSupplierBalance', 'OrganizationBalance'),
        migrations.RenameModel('FuelSupplierHistory', 'OrganizationHistory'),
        migrations.RenameModel('FuelSupplierStatus', 'OrganizationStatus'),

    ]
