# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171116_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='api.OrganizationType'),
        ),
        migrations.AlterField(
            model_name='credittradestatus',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credittradetype',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credittradezeroreason',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationactionstype',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationbalance',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstatus',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='displayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
