# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20171120_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittrade',
            name='fairMarketValuePerCredit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='credittradehistory',
            name='newFairMarketValuePerCredit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=999, null=True),
        ),
    ]
