# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 18:38
from __future__ import unicode_literals

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_historical_data_entry_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.CharField(max_length=4000)),
                ('is_read', models.BooleanField(default=False)),
                ('is_warning', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_notificationmessage_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('originating_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related_credit_transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CreditTrade')),
                ('related_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Organization')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_notificationmessage_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_message',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
