# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notificationmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmessage',
            old_name='related_credit_transfer',
            new_name='related_credit_trade',
        ),
    ]
