# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20171120_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='update_user',
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
