# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180822_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='related_credit_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CreditTrade'),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='related_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Organization'),
        ),
    ]
