# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180822_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
