# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 18:58
from __future__ import unicode_literals

import api.notifications.notifications
import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_notificationmessage_related_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('notification_type', models.CharField(choices=[(api.notifications.notifications.NotificationType('Credit Trade Created'), 'Credit Trade Created'), (api.notifications.notifications.NotificationType('Credit Trade Signed 1/2'), 'Credit Trade Signed 1/2'), (api.notifications.notifications.NotificationType('Credit Trade Signed 2/2'), 'Credit Trade Signed 2/2')], max_length=128)),
                ('channel', models.CharField(choices=[(api.notifications.notifications.NotificationChannel('In-Application'), 'In-Application'), (api.notifications.notifications.NotificationChannel('SMS'), 'SMS'), (api.notifications.notifications.NotificationChannel('Email'), 'Email')], max_length=64)),
                ('enabled', models.BooleanField()),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_notificationsubscription_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_notificationsubscription_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_subscription',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='originating_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_originating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
