# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20171218_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
