# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_usercreationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreationrequest',
            old_name='created',
            new_name='is_mapped',
        ),
        migrations.AlterField(
            model_name='usercreationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creation_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
