# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20181024_2106'),
        ('api', '0039_update_fs_admin_permissions'),
    ]

    operations = [
    ]
