# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20181217_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfileattachment',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=260),
            preserve_default=False,
        ),
    ]
