# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_documentfileattachment_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creating_organization',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='creating_organization',
        ),
    ]
