# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-20 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_document_data_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenthistory',
            old_name='modifying_user_role',
            new_name='user_role',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='modifying_user',
        ),
    ]
