# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_role_permission_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='display_name',
            field=models.CharField(db_column='display_name', blank=True, null=True, max_length=500)),
        migrations.RenameField(
            model_name='User',
            old_name='display_name',
            new_name='_display_name'
        )
    ]
