# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190103_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authorization_directory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authorization_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authorization_guid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authorization_id',
        ),
    ]
