# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_documentcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='comment',
        ),
    ]
