# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20190114_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfileattachment',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
