# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations import RunPython
import django.db.models.deletion


def remove_user_role(_apps, _schema_editor):
    migrations.RemoveField(
        model_name='documenthistory',
        name='user_role'
    )


def add_user_role(_apps, _schema_editor):
    migrations.AddField(
        model_name='documenthistory',
        name='user_role',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_history_roles', to='api.Role'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_permissions_remove_view_compliance_periods'),
    ]

    operations = [
        RunPython(remove_user_role, add_user_role)
    ]
