# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_rename_fuel_supply_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenthistory',
            name='user_role'
        ),
    ]
