# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_notificationmessage_related_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfileattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_attachments', to='api.Document'),
        ),
    ]
