# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_add_document_status_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='record_number',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='record_number',
        ),
        migrations.AddField(
            model_name='documentfileattachment',
            name='record_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
