# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20190211_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittradehistory',
            name='is_internal_history_record',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='update_timestamp',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='update_user',
        ),
    ]
