# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_add_fuel_code_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcode',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.FuelCodeStatus'),
            preserve_default=False,
        ),
    ]
