# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_initial_transport_modes_and_approved_fuels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='approvedfuel',
            table='approved_fuel_type',
        ),
        migrations.AlterModelTable(
            name='transportmode',
            table='fuel_transport_mode_type',
        ),
    ]
