# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20190305_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreationrequest',
            name='external_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usercreationrequest',
            name='keycloak_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='usercreationrequest',
            unique_together=set([('keycloak_email', 'external_username')]),
        ),
    ]
