# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_add_approved_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
