# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 23:18
from __future__ import unicode_literals

import api.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20190329_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittrade',
            name='fair_market_value_per_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[api.validators.CreditTradeFairMarketValueValidator]),
        ),
    ]
