# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20190329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcode',
            name='fuel_code_version_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='fuelcode',
            unique_together=set([('fuel_code', 'fuel_code_version', 'fuel_code_version_minor')]),
        ),
    ]
