# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 19:42
from __future__ import unicode_literals

import db_comments.model_mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_add_fuel_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyEffectivenessRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energyeffectivenessratio_CREATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'energy_effectiveness_ratio',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='approvedfuel',
            name='credit_calculation_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energyeffectivenessratio',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_effective_ratio', to='api.ApprovedFuel'),
        ),
        migrations.AddField(
            model_name='energyeffectivenessratio',
            name='fuel_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='energy_effective_ratio', to='api.FuelClass'),
        ),
        migrations.AddField(
            model_name='energyeffectivenessratio',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energyeffectivenessratio_UPDATE_USER', to=settings.AUTH_USER_MODEL),
        ),
    ]
