# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 17:36
from __future__ import unicode_literals

import db_comments.model_mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20190404_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energydensity_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_density', to='api.ApprovedFuel')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energydensity_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'energy_density',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
