# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20190408_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedfuel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
