# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_update_credit_calculation_fuel_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydensity',
            name='unit_of_measure',
        ),
        migrations.AlterField(
            model_name='approvedfuel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
