# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 15:51
from __future__ import unicode_literals

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20190411_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCarbonIntensityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_defaultcarbonintensitycategory_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_defaultcarbonintensitycategory_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'default_carbon_intensity_category',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='EnergyDensityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energydensitycategory_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energydensitycategory_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'energy_density_category',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='EnergyEffectivenessRatioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energyeffectivenessratiocategory_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_energyeffectivenessratiocategory_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'energy_effectiveness_ratio_category',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.RemoveField(
            model_name='defaultcarbonintensity',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='energydensity',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='energyeffectivenessratio',
            name='fuel',
        ),
        migrations.AddField(
            model_name='defaultcarbonintensity',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='default_carbon_intensity', to='api.DefaultCarbonIntensityCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energydensity',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='energy_density', to='api.EnergyDensityCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyeffectivenessratio',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='energy_effective_ratio', to='api.EnergyEffectivenessRatioCategory'),
            preserve_default=False,
        ),
    ]
