# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedfuel',
            name='default_carbon_intensity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fuel', to='api.DefaultCarbonIntensityCategory'),
        ),
        migrations.AddField(
            model_name='approvedfuel',
            name='energy_density_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fuel', to='api.EnergyDensityCategory'),
        ),
        migrations.AddField(
            model_name='approvedfuel',
            name='energy_effectiveness_ratio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fuel', to='api.EnergyEffectivenessRatioCategory'),
        ),
        migrations.AddField(
            model_name='approvedfuel',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fuel', to='api.UnitOfMeasure'),
        ),
    ]
