# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_add_unit_of_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedfuel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
