# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20190425_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedfuel',
            name='is_partially_renewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelcode',
            name='renewable_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
