# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 21:44
from __future__ import unicode_literals

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_expecteduse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutosavedFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, verbose_name='key')),
                ('data', models.TextField(null=True, verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'autosaved_form_data',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AlterUniqueTogether(
            name='autosavedformdata',
            unique_together=set([('user', 'key')]),
        ),
    ]
