# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20190528_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecrecord',
            name='expected_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ExpectedUse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecrecord',
            name='fuel_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.FuelClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecrecord',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ApprovedFuel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecrecord',
            name='rationale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
