# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 18:23
from __future__ import unicode_literals

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_notionaltransfertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedFuelProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_approvedfuelprovision_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ApprovedFuel')),
            ],
            options={
                'db_table': 'approved_fuel_provision',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='CarbonIntensityDeterminationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('display_order', models.IntegerField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('the_type', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_carbonintensitydeterminationtype_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_carbonintensitydeterminationtype_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carbon_intensity_determination_type',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ProvisionOfTheAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_provisionoftheact_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('determination_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_provisions', to='api.CarbonIntensityDeterminationType')),
                ('fuel', models.ManyToManyField(through='api.ApprovedFuelProvision', to='api.ApprovedFuel')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_provisionoftheact_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fuel_provisions',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='approvedfuelprovision',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ProvisionOfTheAct'),
        ),
        migrations.AddField(
            model_name='approvedfuelprovision',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_approvedfuelprovision_UPDATE_USER', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='approvedfuelprovision',
            unique_together=set([('fuel', 'provision')]),
        ),
    ]
