# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_fix_renewable_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedfuelprovision',
            name='determination_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.CarbonIntensityDeterminationType'),
        ),
        migrations.AddField(
            model_name='provisionoftheact',
            name='provision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='approvedfuelprovision',
            unique_together=set([('fuel', 'provision', 'determination_type')]),
        ),
    ]
