# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_auto_20190606_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionoftheact',
            name='determination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provision_act', to='api.CarbonIntensityDeterminationType'),
        ),
        migrations.AlterModelTable(
            name='approvedfuelprovision',
            table='carbon_intensity_fuel_determination',
        ),
        migrations.AlterModelTable(
            name='provisionoftheact',
            table='provision_act',
        ),
    ]
