# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_update_approved_fuel_xref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonintensitydeterminationtype',
            name='description',
        ),
        migrations.AlterField(
            model_name='approvedfuelprovision',
            name='determination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CarbonIntensityDeterminationType'),
        ),
        migrations.AlterField(
            model_name='provisionoftheact',
            name='provision',
            field=models.CharField(max_length=100),
        ),
    ]
