# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20190606_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionoftheact',
            name='determination_type',
        ),
    ]
