# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_remove_provisionoftheact_determination_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedfuelprovision',
            old_name='provision',
            new_name='provision_act',
        ),
        migrations.AlterUniqueTogether(
            name='approvedfuelprovision',
            unique_together=set([('fuel', 'provision_act', 'determination_type')]),
        ),
    ]
