# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_edit_organization_address_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='primary',
        ),
    ]
