# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_schedule_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittradecomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
