# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20190718_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulecrecord',
            options={},
        ),
    ]
