# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 22:29
from __future__ import unicode_literals

from api.models.SigningAuthorityAssertion import SigningAuthorityAssertion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20190718_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingauthorityassertion',
            name='description',
            field=models.CharField(choices=[(SigningAuthorityAssertion.AssertionModules('credit_trade'), 'CREDIT_TRADE'), (SigningAuthorityAssertion.AssertionModules('compliance_report'), 'COMPLIANCE_REPORTING')], default='credit_trade', max_length=50),
        ),
    ]
