# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-29 18:10
from __future__ import unicode_literals

from api.models.SigningAuthorityAssertion import SigningAuthorityAssertion
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingauthorityassertion',
            name='module',
            field=models.CharField(choices=[(SigningAuthorityAssertion.AssertionModules('credit_trade'), 'CREDIT_TRADE'), (SigningAuthorityAssertion.AssertionModules('compliance_report'), 'COMPLIANCE_REPORTING')], default='credit_trade', max_length=50),
        ),
        migrations.AddField(
            model_name='signingauthorityconfirmation',
            name='compliance_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmations', to='api.ComplianceReport'),
        ),
        migrations.AlterField(
            model_name='signingauthorityconfirmation',
            name='credit_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmations', to='api.CreditTrade'),
        ),
    ]
