# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 18:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20190729_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
