# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 19:41
from __future__ import unicode_literals

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_add_compliance_report_new_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReportWorkflowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('analyst_status', models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ComplianceReportStatus', to_field='status')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_compliancereportworkflowstate_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('director_status', models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ComplianceReportStatus', to_field='status')),
                ('fuel_supplier_status', models.ForeignKey(default='Draft', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ComplianceReportStatus', to_field='status')),
                ('manager_status', models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ComplianceReportStatus', to_field='status')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_compliancereportworkflowstate_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_report_workflow_state',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='status',
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='status_django_pacifier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_report', to='api.ComplianceReportWorkflowState'),
        ),
    ]
