# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-19 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_auto_20190819_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancereport',
            old_name='status_django_pacifier',
            new_name='status',
        ),
    ]
