# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_auto_20190819_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereporthistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_records', to='api.ComplianceReportWorkflowState'),
        ),
    ]
