# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-09 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_auto_20190829_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='credit_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliance_report', to='api.CreditTrade'),
        ),
    ]
