# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_auto_20190829_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportstatus',
            name='status',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
