# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_add_request_supplemental_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='supplements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_reports', to='api.ComplianceReport'),
        ),
    ]
