# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_compliancereport_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
