# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_update_roles_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_role',
            field=models.BooleanField(default=False),
        ),
    ]
