# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_auto_20190930_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='supplemental_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
