# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_update_guest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesummary',
            name='diesel_class_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulesummary',
            name='diesel_class_previously_retained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulesummary',
            name='gasoline_class_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulesummary',
            name='gasoline_class_previously_retained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
