# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_auto_20191017_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmilestone',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='documentmilestone',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentmilestone',
            name='update_user',
        ),
        migrations.AddField(
            model_name='document',
            name='milestone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='milestone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentMilestone',
        ),
    ]
