# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_audit_additional_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelcode',
            unique_together=set([('fuel_code', 'fuel_code_version', 'fuel_code_version_minor', 'status')]),
        ),
    ]
