# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_update_compliance_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesummary',
            name='credits_offset_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulesummary',
            name='credits_offset_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
