# Generated by Django 3.2.10 on 2022-11-02 22:20

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_auto_20210421_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportsnapshot',
            name='compliance_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.compliancereport'),
        ),
        migrations.AlterField(
            model_name='compliancereportsnapshot',
            name='snapshot',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='compliancereportworkflowstate',
            name='analyst_status',
            field=models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.compliancereportstatus', to_field='status'),
        ),
        migrations.AlterField(
            model_name='compliancereportworkflowstate',
            name='director_status',
            field=models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.compliancereportstatus', to_field='status'),
        ),
        migrations.AlterField(
            model_name='compliancereportworkflowstate',
            name='fuel_supplier_status',
            field=models.ForeignKey(default='Draft', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.compliancereportstatus', to_field='status'),
        ),
        migrations.AlterField(
            model_name='compliancereportworkflowstate',
            name='manager_status',
            field=models.ForeignKey(default='Unreviewed', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.compliancereportstatus', to_field='status'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='api.documentcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
