# Generated by Django 3.2.10 on 2022-11-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_auto_20221102_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
