# Generated by Django 3.2.16 on 2023-02-02 20:59

import db_comments.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_user_keycloak_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('keycloak_email', models.EmailField(max_length=254)),
                ('external_username', models.CharField(blank=True, max_length=150, null=True)),
                ('keycloak_user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('is_login_successful', models.BooleanField(default=False)),
                ('login_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_userloginhistory_CREATE_USER', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_userloginhistory_UPDATE_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_history',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
