# Generated by Django 3.2.18 on 2023-03-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_create_user_login_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsheetinput',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsheetinput',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
