# Generated by Django 3.2.18 on 2023-03-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20230312_0823'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE organization_address SET address_line_2 = address_line_2 || ' ' || address_line_3;"
        ),
        migrations.RunSQL(
            "UPDATE organization_address SET state = state || ' ' || county"
        ),
    ]
