# Generated by Django 3.2.18 on 2023-03-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20230312_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='organizationaddress',
            name='county',
        ),
    ]
