# Generated by Django 3.2.18 on 2023-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_auto_20230316_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_address_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_representativename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='attorney_street_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
