# Generated by Django 3.2.18 on 2023-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_auto_20230321_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesummary',
            name='credits_offset_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]