# Stage 1: Use yarn to build the app
FROM artifacts.developer.gov.bc.ca/docker-remote/node:16 as builder
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install -g npm@9.1.1 \
    && npm install --omit=dev \
    && npm install -g webpack webpack-cli
RUN npm link webpack 
RUN npm link webpack-cli
RUN npm run build

# Stage 2: Copy the JS React SPA into the Nginx HTML directory
FROM artifacts.developer.gov.bc.ca/docker-remote/bitnami/nginx:1.21.6
COPY ./nginx.conf /opt/bitnami/nginx/conf/
COPY --from=builder /usr/src/app/build /app
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
