# Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
# user              www www;  ## Default: nobody

worker_processes  auto;
error_log         /dev/stderr info;
pid               /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format    main '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status  $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
    access_log    /dev/stdout main;
    add_header    X-Frame-Options SAMEORIGIN;

    client_body_temp_path  /tmp/nginx/client_body;
    proxy_temp_path        /tmp/nginx/proxy;
    fastcgi_temp_path      /tmp/nginx/fastcgi;
    scgi_temp_path         /tmp/nginx/scgi;
    uwsgi_temp_path        /tmp/nginx/uwsgi;

    sendfile           on;
    tcp_nopush         on;
    tcp_nodelay        off;
    gzip               on;
    gzip_http_version  1.0;
    gzip_comp_level    2;
    gzip_proxied       any;
    gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
    keepalive_timeout  65;
    ssl_protocols      TLSv1.2 TLSv1.3;
    ssl_ciphers        HIGH:!aNULL:!MD5;
    client_max_body_size 80M;
    server_tokens off;

    absolute_redirect  off;
    port_in_redirect   off;

    # HTTP Server
    server {
        # Port to listen on, can also be set in IP:PORT format
        listen  8080;

        root /usr/share/nginx/html;

        index  index.html;

        location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to redirecting to index.html            
            try_files $uri $uri/ $uri.html /index.html;
        }

        location ~* \.(?:css|js|jpg|svg)$ {
            expires 30d;
            add_header Cache-Control "public";
        }        

        location ~* \.(?:json)$ {
            expires 1d;
            add_header Cache-Control "public";
        }        

        #location /status {
        #    stub_status on;
        #    access_log   off;
        #    allow 127.0.0.1;
        #    deny all;
        #}
    }
}
