---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tfrs-frontend-angular-app
  creationTimestamp:
parameters:
- name: NAME
  description: tfrs
  value: tfrs
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: GIT_URL
  displayName:
  description: tfrs repo
  required: true
- name: GIT_REF
  displayName:
  description: tfrs branch name of the pr
  required: true  
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the frontend angular image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-frontend-angular-app
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: "" 
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${NAME}-frontend-angular-app${SUFFIX}
    creationTimestamp:
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
      contextDir: frontend
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-16:1-71
          namespace: 0ab226-tools
        pullSecret:
          name: tfrs-image-pull-secret
        forcePull: true
        noCache: true          
        env:
          - name: ARTIFACTORY_USER
            valueFrom:
              secretKeyRef:
                name: artifacts-tfrs-artifactory-service-account-wofwpt
                key: username
          - name: ARTIFACTORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: artifacts-tfrs-artifactory-service-account-wofwpt
                key: password
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-frontend-angular-app:${VERSION}
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        memory: 2Gi
    postCommit: {}
    nodeSelector:
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
  status:
    lastVersion: 0
