---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tfrs-frontend-dc
  creationTimestamp:
parameters:
- name: NAME
  description: tfrs
  value: tfrs
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: FRONTEND_HOST
  displayName: Frontend route host name
  description: 
  required: true
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}-frontend${SUFFIX}
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}-frontend${SUFFIX}
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}${SUFFIX}
    creationTimestamp:
    labels:
      frontend: 'true'
    annotations:
      haproxy.router.openshift.io/timeout: 1200s
  spec:
    host: ${FRONTEND_HOST}
    to:
      kind: Service
      name: ${NAME}-frontend${SUFFIX}
      weight: 100
    port:
      targetPort: web
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

