---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: client-bc
  creationTimestamp:
parameters:
- name: NAME
  description: tfrs
  value: tfrs
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: GIT_URL
  displayName:
  description: tfrs repo
  required: true
- name: GIT_REF
  displayName:
  description: tfrs branch name of the pr
  required: true
objects:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${NAME}-frontend${SUFFIX}
    creationTimestamp:
    annotations:
      description: Defines how to build the front end image
  spec:
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Dockerfile
      dockerfile: |-
        FROM ${{NAME}}-frontend-angular-app${{SUFFIX}}:${{VERSION}}
        COPY * /tmp/app/dist/
        CMD  /usr/libexec/s2i/run
      images:
      - from:
          kind: ImageStreamTag
          name: ${NAME}-frontend-angular-app${SUFFIX}:${VERSION}
        as:
        paths:
        - sourcePath: "/opt/app-root/src/public/."
          destinationDir: tmp
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-runtime:20210115
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-frontend${SUFFIX}:${VERSION}
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
    postCommit: {}
    nodeSelector:
  status:
    lastVersion: 0
