apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: frontend-dc
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description: image tag name for output
    required: true
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: Environment name, dev, test and prod
    required: true
  - name: NAMESPACE
    displayName: namespace
    description: namespace
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: KEYCLOAK_AUTHORITY
    displayName: keycloak authority
    description: keycloak authority
    required: true
  - name: KEYCLOAK_CLIENT_ID
    displayName: keycloak client id
    description: keycloak client id
    required: true
  - name: KEYCLOAK_CALLBACK_URL
    displayName: keycloak callback url
    description: keycloak callback url
    required: true
  - name: KEYCLOAK_LOGOUT_URL
    displayName: keycloak logout url
    description: keycloak logout url
    required: true
  - name: SITEMINDER_LOGOUT_URL
    displayName: siteminder logout url
    description: siteminder logout url
    required: true       
  - name: BACKEND_HOST
    displayName: backend host
    description: backend host
    required: true
  - name: DEBUG_ENABLED
    displayName: debug enabled
    description: debug enabled
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the client / front end image
      labels:
        shared: "true"
      creationTimestamp: null
      name: ${NAME}-frontend
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${NAME}-frontend-features${SUFFIX}
      creationTimestamp:
    data:
      features.js: |
        window.tfrs_config = {
          "keycloak.realm": "standard",
          "keycloak.client_id": "${KEYCLOAK_CLIENT_ID}",
          "keycloak.auth_url": "${KEYCLOAK_AUTHORITY}",
          "keycloak.callback_url": "${KEYCLOAK_CALLBACK_URL}",
          "keycloak.post_logout_url": "${KEYCLOAK_LOGOUT_URL}",
          "keycloak.siteminder_logout_url": "${SITEMINDER_LOGOUT_URL}",
          "debug.enabled": ${DEBUG_ENABLED},
          "secure_document_upload.enabled": true,
          "secure_document_upload.max_file_size": 50000000,
          "fuel_codes.enabled": true,
          "keycloak.custom_login": true,
          "credit_transfer.enabled": true,
          "compliance_reporting.enabled": true,
          "compliance_reporting.starting_year": 2017,
          "compliance_reporting.create_effective_date": "2019-01-01",
          "credit_calculation_api.enabled": true,
          "exclusion_reports.enabled": true,
          "exclusion_reports.create_effective_date": "2019-01-01",
          "api_base": "https://${BACKEND_HOST}/api",

          "tear_down.bceid.widgets.balance": true,
          "tear_down.bceid.widgets.feedback": true,
          "tear_down.bceid.widgets.website": true,
          "tear_down.bceid.widgets.creditTransactions": true,
          "tear_down.bceid.widgets.fileSubmissions": true,
          "tear_down.bceid.header.creditInformation": true,
          "tear_down.bceid.navigation.transactions": true,
          "tear_down.bceid.navigation.fileSubmissions": true,
          "tear_down.bceid.navigation.helpLink": true,
          "tear_down.bceid.organization.creditInformation": true,
          "tear_down.bceid.organization.roles.fileSubmission": true,
          "tear_down.bceid.organization.roles.creditTransfers": true,
          "tear_down.idir.widgets.balance": true,
          "tear_down.idir.widgets.creditTransactions": true,
          "tear_down.idir.widgets.fileSubmissions": true,
          "tear_down.idir.navigation.transactions": true,
          "tear_down.idir.navigation.fileSubmissions": true,
          "tear_down.idir.navigation.helpLink": true,
          "tear_down.idir.organizations.tableColumns.complianceUnits": true,
          "tear_down.idir.organizations.tableColumns.inReserve": true,
          "tear_down.idir.organization.creditInformation": true
        };
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}-frontend${SUFFIX}
      annotations:
        description: Defines how to deploy the frontend application
      creationTimestamp: null
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      automountServiceAccountToken: false
      selector:
        name: ${NAME}-frontend${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${NAME}-frontend${SUFFIX}
        spec:
          volumes:
            - name: ${NAME}-frontend-features${SUFFIX}
              configMap:
                name: ${NAME}-frontend-features${SUFFIX}
          containers:
            - name: frontend
              env: null
              image:
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: ${NAME}-frontend-features${SUFFIX}
                  mountPath: /app/static/js/config
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: RABBITMQ_VHOST
                  value: tfrs-vhost
                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: tfrs-rabbitmq-app
                      key: username
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tfrs-rabbitmq-app
                      key: password
                - name: RABBITMQ_HOST
                  value: tfrs-rabbitmq.${NAMESPACE}.svc.cluster.local
                - name: RABBITMQ_PORT
                  value: '5672'
              livenessProbe:
                failureThreshold: 10
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 3
              readinessProbe:
                failureThreshold: 10
                initialDelaySeconds: 20
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: ${NAME}-frontend:${VERSION}
            lastTriggeredImage:
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
