# Default values for tfrs-scan-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 25m
    memory: 50Mi