version: '3'

services:
    test-db:
        build:
            dockerfile: Dockerfile-postgres
            context: ./postgres
        expose:
            - 5432
    test-django:
        environment:
          - DATABASE_NAME=tfrs
          - DATABASE_USER=tfrs
          - DATABASE_PASSWORD=development_only
          - DATABASE_ENGINE=postgresql
          - DATABASE_SERVICE_NAME=postgresql
          - POSTGRESQL_SERVICE_HOST=test-db
          - POSTGRESQL_SERVICE_PORT=5432
        depends_on:
            - test-db
        build:
            dockerfile: Dockerfile-django
            context: ./backend
        command: >
                bash -c
                "pip install -q -r requirements.txt &&
                /wfi/wait-for-it.sh -t 14400 test-db:5432 &&
                python3 manage.py test -v 2 --testrunner django.test.runner.DiscoverRunner"
        volumes:
            - ./backend:/app
    test-minio:
      image: minio/minio
      volumes:
        - minio_data:/export
      environment:
        MINIO_ACCESS_KEY: 296e92217fa3479aaf9cc9641fdb6e0a
        MINIO_SECRET_KEY: 778eecb24d7743b5a1b56bbf36a29d62
      ports:
        - 9000:9000
      command: "server /export"
volumes:
    minio_data:
