kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: tfrs-scan-handler{{ .Values.suffix }}
  labels:
    {{- include "tfrs-scan-handler.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - scan-handler
        from:
          kind: ImageStreamTag
          name: tfrs-scan-handler:{{ .Values.scanHandlerImageTagName }}
    - type: ConfigChange
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  test: false
  selector:
    {{- include "tfrs-scan-handler.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "tfrs-scan-handler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: scan-handler
          env:
            - name: RABBITMQ_VHOST
              value: {{ .Values.rabbitmqVHost }}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-app
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-app
                  key: password
            - name: RABBITMQ_HOST
              value: tfrs-rabbitmq.{{ .Values.envName }}.svc.cluster.local
            - name: RABBITMQ_PORT
              value: '5672'
            - name: DATABASE_SERVICE_NAME
              value: {{ .Values.databaseServiceHostName }}
            - name: DATABASE_ENGINE
              value: postgresql
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: tfrs-patroni-app
                  key: app-db-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: tfrs-patroni-app
                  key: app-db-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tfrs-patroni-app
                  key: app-db-password
          resources:
{{ toYaml .Values.resources | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
