FROM --platform=linux/amd64 python:3.7-buster
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

RUN apt-get update
RUN apt-get install -y git supervisor

# Add necessary files and clone repositories
ADD https://github.com/vishnubob/wait-for-it/compare/master...HEAD /dev/null
RUN git clone https://github.com/vishnubob/wait-for-it.git /wfi