# Use an official Python runtime as a parent image
FROM artifacts.developer.gov.bc.ca/docker-remote/python:3.9.20-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY . /app/

RUN pwd && \
    ls -l

RUN pip install --upgrade pip && \ 
    pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8080

# Start the Django server
CMD ["gunicorn", "wsgi", "--config", "gunicorn.cfg.py"]
