def result = 0;

node('python') {
    stage('Unit Test') {
        checkout scm
        try {
            sh 'cd backend && pip install --upgrade pip && pip install -r requirements.txt'
            sh 'cd backend && coverage erase && coverage run --source=. manage.py test && coverage html && coverage xml'
        } catch(Throwable t) {
            result = 1;
            mail (from: "${EMAIL_FROM}", to: "${EMAIL_TO}", subject: "FYI: Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) unit test failed", body: "See ${env.BUILD_URL} for details. ");
        } finally {
            if(fileExists('backend/htmlcov/index.html')) {
                publishHTML (target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'backend/htmlcov',
                    reportFiles: 'index.html',
                    reportName: "Unit Test Code Coverage Report" ])
            }
        }

    }
}
        
echo "result is ${result}"
if (result != 0) {
    echo "[FAILURE] Unit Test stage failed"
    currentBuild.result = 'FAILURE'
    return
}
        
node('maven') {
    
    stage('Build') {
        openshiftBuild bldCfg: 'tfrs', showBuildLogs: 'true'
        echo ">> Getting Image Hash"
        IMAGE_HASH = sh (
            script: 'oc get istag tfrs:latest -o template --template="{{.image.dockerImageReference}}"|awk -F ":" \'{print $3}\'',
 	            returnStdout: true).trim()
        echo ">> IMAGE_HASH: $IMAGE_HASH"
    }

    stage('Deploy to Test') {
        input "Deploy to Test?"
        echo "Deploying to Test: ${BUILD_ID}"
        openshiftTag destStream: 'tfrs', verbose: 'true', destTag: 'test', srcStream: 'tfrs', srcTag: "${IMAGE_HASH}"
        openshiftVerifyDeployment depCfg: 'tfrs', namespace: 'mem-tfrs-test', replicaCount: 1, verbose: 'false'
    }
    
    stage('Deploy to Prod') {
        input "Deploy to Prod?"
        echo "Deploying to Prod: ${BUILD_ID}"
        openshiftTag destStream: 'tfrs', verbose: 'true', destTag: 'prod', srcStream: 'tfrs', srcTag: "${IMAGE_HASH}"
        openshiftVerifyDeployment depCfg: 'tfrs', namespace: 'mem-tfrs-prod', replicaCount: 1, verbose: 'false'
    }    

}
