# Default values for itvr-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 60m
    memory: 60Mi
  requests:
    cpu: 30m
    memory: 30Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 90

env:
  emailSendingEnabled: true
  djangoDebug: true
  databaseServiceName: tfrs-spilo
  postgresqlServiceHost: tfrs-spilo.0ab226-dev.svc.cluster.local
  rabbitmqHost: tfrs-rabbitmq.0ab226-dev.svc.cluster.local
  minioEndpoint: tfrs-minio-test.apps.silver.devops.gov.bc.ca:443
  documentsApiEnabled: true
  minioSecretName: tfrs-minio-test
  minioAccessKey: MINIO_ACCESS_KEY
  minioSecretKey: MINIO_SECRET_KEY
  fuelCodesApiEnabled: true
  creditCalculationApiEnabled: true
  complianceReportingApiEnabled: true
  exclusionReportsApiEnabled: true
  wellKnownEndpoint: https://test.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration
