# Default values for itvr-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# backendImageTagName is not in  this file, it comes as a argument from the helm command line
# helm template command
# helm template  --set backendImageTagName=dev-main-release-jan-2024 -f ./values-dev-jan.yaml tfrs-backend-dev-jan .
# helm -n <namespace> --set backendImageTagName=dev-main-release-jan-2024 -f ./values-dev-jan.yaml upgrade tfrs-backend-dev-jan .

replicaCount: 1

resources:
  limits:
    cpu: 400m
    memory: 1200Mi
  requests:
    cpu: 200m
    memory: 600Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 90

env:
  emailSendingEnabled: true
  djangoDebug: true
  documentsApiEnabled: true
  fuelCodesApiEnabled: true
  creditCalculationApiEnabled: true
  complianceReportingApiEnabled: true
  exclusionReportsApiEnabled: true
