---
kind: Template
apiVersion: v1
metadata:
  name: clamav
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: clamav
    generation: 1
    creationTimestamp: 
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: clamav
    creationTimestamp: 
    labels:
      app: clamav
      name: clamav
      template: clamav
  spec:
    triggers: []
    runPolicy: Serial
    source:
      type: Git
      git:
        ref: add-ca-cert
        uri: https://github.com/bcgov/docker-clamav.git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: true
    output:
      to:
        kind: ImageStreamTag
        name: clamav:latest
    resources: {}
    postCommit: {}
    nodeSelector: {}
  status:
    lastVersion: 0
