export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';

export const REQUEST_AUTH = 'REQUEST_AUTH';
export const REQUEST_AUTH_SUCCESS = 'REQUEST_AUTH_SUCCESS';
export const REQUEST_AUTH_FAILURE = 'REQUEST_AUTH_FAILURE';