export const GET_ACCOUNT_ACTIVITY = 'GET_ACCOUNT_ACTIVITY';
export const ACCEPT_CREDIT_TRANSFER = 'ACCEPT_CREDIT_TRANSFER';
export const GET_FUEL_SUPPLIERS = 'GET_FUEL_SUPPLIERS';
export const SEARCH_FUEL_SUPPLIERS = 'SEARCH_FUEL_SUPPLIERS';
export const ADD_FUEL_SUPPLIER = 'ADD_FUEL_SUPPLIER';