spilo:

  replicaCount: 2

  credentials:
    useExistingSecret: true
    existingSecret:
      name: tfrs-patroni-admin
      superuserKey: password-superuser
      adminKey: password-admin
      standbyKey: password-standby

  continuousArchive:
    enabled: true
    scheduleCronJob: "0 */3 * * *"
    retainBackups: 3
    storage: s3
    s3:
      bucket: tfrsts/postgresbackup
      secretName: tfrs-db-backup-s3

  shipLogs:
    enabled: false
#    s3:
#      bucket: s3://tfrsts
#      shipSchedule: 0 7 * * *

  persistentVolume:
    size: 2Gi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 120m
      memory: 400Mi
    requests:
      cpu: 60m
      memory: 200Mi  

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true 
      initialDelaySeconds: 60
      failureThreshold: 20         

