spilo:

  replicaCount: 1

  credentials:
    useExistingSecret: true
    existingSecret:
      name: tfrs-patroni-admin
      superuserKey: password-superuser
      adminKey: password-admin
      standbyKey: password-standby

  continuousArchive:
    enabled: false
    scheduleCronJob: "0 10 * * *"
    retainBackups: 3
    storage: s3
    s3:
      bucket: tfrsdv
      secretName: tfrs-db-backup-s3

  shipLogs:
    enabled: false
#    s3:
#      bucket: s3://tfrsdv
#      shipSchedule: 0 7 * * *

  persistentVolume:
    size: 1Gi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 200m
      memory: 600Mi
    requests:
      cpu: 100m
      memory: 300Mi  

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true 
      initialDelaySeconds: 60
      failureThreshold: 20         