kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: clamav-signature-db
  labels: {{ include "tfrs-clamav.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: netapp-file-standard

