apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"d49aaa14-e506-11e7-bfd0-0a58ac332043","leaseDurationSeconds":15,"acquireTime":"2018-01-09T21:25:22Z","renewTime":"2018-01-09T21:25:26Z","leaderTransitions":0}'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-block
      volume.beta.kubernetes.io/storage-provisioner: gluster.org/glusterblock
    creationTimestamp: 2018-01-09T21:25:22Z
    name: jenkins-cns
    namespace: mem-tfrs-tools
    resourceVersion: "310808467"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/jenkins-cns
    uid: 99698347-f583-11e7-9ace-0050568348cc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-99698347-f583-11e7-9ace-0050568348cc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-01-19T21:36:42Z
    name: jenkins-cns2
    namespace: mem-tfrs-tools
    resourceVersion: "319957054"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/jenkins-cns2
    uid: d753561f-fd60-11e7-b70e-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-d753561f-fd60-11e7-b70e-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-01-10T18:31:42Z
    name: postgresql-sonarqube-cns
    namespace: mem-tfrs-tools
    resourceVersion: "311322996"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/postgresql-sonarqube-cns
    uid: 814c86b8-f634-11e7-9f70-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-814c86b8-f634-11e7-9f70-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-01-10T18:31:11Z
    name: sonarqube-data-cns
    namespace: mem-tfrs-tools
    resourceVersion: "311322696"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/sonarqube-data-cns
    uid: 6eefa34f-f634-11e7-9f70-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: pvc-6eefa34f-f634-11e7-9f70-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
