version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  
jobs:
  build: 
    working_directory: ~/project/backend
    docker:
      - image: python:3.6.9-stretch
    steps:
      - checkout
      - run:
          name: "Install required packages"
          command: pip install --upgrade pip && pip install -r requirements.txt && pip install nose-exclude
