version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  
jobs:
  build: 
    docker:
      - image: python:3.6.9-stretch
    steps:
      - checkout
      - run:
          name: "cd to backend folder"
          command: cd backend
      - run:
          name: "Install required packages"
          command: |
            pwd
            pip install --upgrade pip && pip install -r requirements.txt && pip install nose-exclude
            python manage.py collectstatic
      - run:
          name: "Run unit tests"
          command: |
            pwd
            python manage.py test --noinput -c nose.cfg
            mkdir test_results
            mv coverage.xml test_results
            mv nosetests.xml test_results
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/nosetests.xml
      - store_artifacts:
          path: test_results/nosetests.xml


