version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  
jobs:
  build: 
    docker:
      - image: python:3.6.9-stretch
    steps:
      - checkout
      - run:
          name: "Install required packages"
          command: |
            cd backend
            pip install --upgrade pip && pip install -r requirements.txt && pip install nose-exclude
            python manage.py collectstatic
      - run:
          name: "Run unit tests"
          command: |
            set +e
            cd backend
            python manage.py test --noinput -c nose.cfg
      - run:
          name: "move test results"
          command: |
            set +e
            cd backend
            mkdir test_results
            cd test_results
            mkdir unit_test
            mkdir coverage
            cd ..
            mv nosetests.xml test_results/unit_test
            mv coverage.xml test_results/coverage
      - store_test_results:
          path:  backend/test_results
      - store_artifacts:
          path: backend/test_results/unit_test/nosetests.xml
      - store_artifacts:
          path: backend/test_results/coverage/coverage.xml



