{{- if .Values.route.createFrontendRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tfrs{{ .Values.suffix }}
  annotations:
    haproxy.router.openshift.io/timeout: 1200s
  labels:
    {{- include "tfrs-frontend.labels" . | nindent 4 }}
spec:
  host: tfrs{{ .Values.suffix }}.apps.silver.devops.gov.bc.ca
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tfrs-frontend{{ .Values.suffix }}
    weight: 100
  wildcardPolicy: None
  {{- end }}
