apiVersion: v1
kind: Service
metadata:
  name: tfrs-frontend{{ .Values.suffix }}
  labels:
    {{- include "tfrs-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  sessionAffinity: None
  selector:
    {{- include "tfrs-frontend.selectorLabels" . | nindent 4 }}
