apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      postgresql10 staging database
objects:
# move ServiceAccount and Role to here, otherwise image pulled may fail because ServiceAccount hasn't been created
- apiVersion: v1
  kind: Secret
  metadata:
    name: tfrs-postgresql-staging
  stringData:
    replication-username: <from prod>
    replication-password: <from prod>
    superuser-username: <from prod>
    superuser-password: <from prod>
    app-db-name: <from prod>
    app-db-username: <from prod>
    app-db-password: <from prod>