apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-hy7p9
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2017-01-31T22:12:09Z
    name: builder
    namespace: mem-tfrs-dev
    resourceVersion: "37131760"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/serviceaccounts/builder
    uid: 4f2acb1f-e802-11e6-a3e3-0050568379a2
  secrets:
  - name: builder-token-vnrju
  - name: builder-dockercfg-hy7p9
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-vuq9e
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2017-01-31T22:12:09Z
    name: default
    namespace: mem-tfrs-dev
    resourceVersion: "37131757"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/serviceaccounts/default
    uid: 4f291e7d-e802-11e6-a3e3-0050568379a2
  secrets:
  - name: default-token-54qx0
  - name: default-dockercfg-vuq9e
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-yzo32
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2017-01-31T22:12:09Z
    name: deployer
    namespace: mem-tfrs-dev
    resourceVersion: "37131764"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/serviceaccounts/deployer
    uid: 4f2e05a9-e802-11e6-a3e3-0050568379a2
  secrets:
  - name: deployer-token-hu564
  - name: deployer-dockercfg-yzo32
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
