negative = 'Cannot be negative'
zero = 'Cannot be zero'
fractional = 'Must be a whole number'
duplicate = 'Duplicate entry'
duplicate_with_row = 'Duplicate entry in row {row}'
missing = 'Missing value'
extra_value = 'Extraneous value'
missing_key = 'Missing value for {key}'
