apiVersion: v1
kind: Service
metadata:
  name: tfrs-backend{{ .Values.suffix }}
  labels:
    {{- include "tfrs-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "tfrs-backend.selectorLabels" . | nindent 4 }}
