apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: nagios-secret
parameters:
  - name: NAGIOS_PASSWORD
    description: nagios password
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: nagios-secret
      labels: {}
    stringData:
      NAGIOS_USER: nagiosadmin
      NAGIOS_PASSWORD: ${NAGIOS_PASSWORD}
