---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: scan-coordinator-dc
  creationTimestamp:
parameters:
- name: ENV_NAME
  displayName: Environment name
  description: 'Valid values: dev, test and prod'
  required: true
- name: SOURCE_IS_NAME
  displayName: The source image stream name
  description: 'The image stream could trigger the deployment, valid values: scan-coordinator-develop
    and scan-coordinator'
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: scan-coordinator
    generation: 62
    creationTimestamp:
    labels:
      app: scan-coordinator
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - scan-coordinator
        from:
          kind: ImageStreamTag
          namespace: mem-tfrs-tools
          name: "${SOURCE_IS_NAME}:${ENV_NAME}"
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: scan-coordinator
      deploymentconfig: scan-coordinator
    template:
      metadata:
        creationTimestamp:
        labels:
          app: scan-coordinator
          deploymentconfig: scan-coordinator
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
        - name: scan-coordinator
          image: ''
          env:
          - name: BYPASS_CLAMAV
            value: 'false'
          - name: CLAMAV_HOST
            value: clamav.mem-tfrs-${ENV_NAME}.svc
          - name: CLAMAV_PORT
            value: '3310'
          - name: AMQP_HOST
            value: rabbit.mem-tfrs-${ENV_NAME}.svc
          - name: AMQP_VHOST
            value: "/tfrs"
          - name: AMQP_PORT
            value: '5672'
          - name: AMQP_USER
            value: tfrs
          - name: MINIO_ENDPOINT
            value: docs-mem-tfrs-${ENV_NAME}.pathfinder.gov.bc.ca:443
          - name: MINIO_USE_SSL
            value: 'true'
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-tfrs
                key: TFRS_PASSWORD
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minioSecretKey
          resources:
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
