---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: scan-coordinator-dc
  creationTimestamp:
parameters:
- name: NAME
  displayName: App name
  description: App name
  value: tfrs
  required: true
- name: SUFFIX
  displayName: suffix
  description: such as -dev-1696, -dev ane etc.
  required: true  
- name: NAMESPACE
  displayName: Environment name
  description: 'Sample values: 0ab226-dev, 0ab226-test and 0ab226-prod'
  required: true
- name: VERSION
  displayName: null
  description: image tag name for output
  required: true
- name: ENV_NAME
  displayName: Environment name
  description: 'Valid values: dev, test and prod'
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the scan coordinator image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-scan-coordinator
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${NAME}-scan-coordinator${SUFFIX}
    creationTimestamp:
    labels:
      name: ${NAME}-scan-coordinator${SUFFIX}
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - scan-coordinator
        from:
          kind: ImageStreamTag
          name: ${NAME}-scan-coordinator:${VERSION}
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      name: ${NAME}-scan-coordinator${SUFFIX}
    template:
      metadata:
        creationTimestamp:
        labels:
          name: ${NAME}-scan-coordinator${SUFFIX}
      spec:
        containers:
        - name: scan-coordinator
          image: ''
          env:
          - name: BYPASS_CLAMAV
            value: 'false'
          - name: CLAMAV_HOST
            value: tfrs-clamav.${NAMESPACE}.svc.cluster.local
          - name: CLAMAV_PORT
            value: '3310'
          - name: AMQP_HOST
            value: tfrs-rabbitmq.${NAMESPACE}.svc.cluster.local
          - name: AMQP_VHOST
            value: "tfrs-vhost"
          - name: AMQP_PORT
            value: '5672'
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: tfrs-rabbitmq-app
                key: username
          - name: MINIO_ENDPOINT
            value: ${NAME}-minio-${ENV_NAME}.apps.silver.devops.gov.bc.ca
          - name: MINIO_USE_SSL
            value: 'true'
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tfrs-rabbitmq-app
                key: password
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-minio-${ENV_NAME}
                key: root-user
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-minio-${ENV_NAME}
                key: root-password
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
