apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: ROOT_PASSWORD
  description: the root password of object storage
  required: true
- name: ROOT_USER
  description: the root user of object storage
  required: true
- name: SERVER_URL
  description: the url of object storage
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: tfrs-object-storage
  stringData:
    root-password: ${ROOT_PASSWORD}
    root-user: ${ROOT_USER}
    server-url: ${SERVER_URL}
