export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

// Credit Transfers
export const GET_CREDIT_TRANSFERS = 'GET_CREDIT_TRANSFERS';
export const RECEIVE_CREDIT_TRANSFERS = 'RECEIVE_CREDIT_TRANSFERS';
export const CREATE_CREDIT_TRANSFER = 'CREATE_CREDIT_TRANSFER';
export const UPDATE_CREDIT_TRANSFER = 'UPDATE_CREDIT_TRANSFER';
export const DELETE_CREDIT_TRANSFER = 'DELETE_CREDIT_TRANSFER';
export const GET_CREDIT_TRANSFER = 'GET_CREDIT_TRANSFER';
export const RECEIVE_CREDIT_TRANSFER = 'RECEIVE_CREDIT_TRANSFER';

// Users
export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER';
export const RECEIVE_LOGGED_IN_USER = 'RECEIVE_LOGGED_IN_USER';
export const ERROR_LOGGED_IN_USER = 'ERROR_LOGGED_IN_USER';

// Organizations
export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const RECEIVE_ORGANIZATION = 'RECEIVE_ORGANIZATION';

export const GET_FUEL_SUPPLIERS = 'GET_FUEL_SUPPLIERS';
export const RECEIVE_FUEL_SUPPLIERS = 'RECEIVE_FUEL_SUPPLIERS';
