export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

// Credit Transfers
export const GET_CREDIT_TRANSFERS = 'GET_CREDIT_TRANSFERS';
export const RECEIVE_CREDIT_TRANSFERS = 'RECEIVE_CREDIT_TRANSFERS';
export const CREATE_CREDIT_TRANSFER = 'CREATE_CREDIT_TRANSFER';
export const UPDATE_CREDIT_TRANSFER = 'UPDATE_CREDIT_TRANSFER';
export const DELETE_CREDIT_TRANSFER = 'DELETE_CREDIT_TRANSFER';
export const GET_CREDIT_TRANSFER = 'GET_CREDIT_TRANSFER';
export const RECEIVE_CREDIT_TRANSFER = 'RECEIVE_CREDIT_TRANSFER';