// Credit Transactions
export const BTN_ACCEPT = 'Accept';
export const BTN_ADD_TO_QUEUE = 'Add to Queue';
export const BTN_APP_CANCEL = 'Cancel';
export const BTN_COMMIT = 'Commit';
export const BTN_CT_CANCEL = 'Cancel';
export const BTN_DELETE = 'Delete';
export const BTN_DELETE_DRAFT = 'Delete Draft';
export const BTN_EDIT_DRAFT = 'Edit Draft';
export const BTN_NO = 'No';
export const BTN_PROCESS = 'Confirm';
export const BTN_PROPOSE = 'Propose';
export const BTN_REFUSE = 'Refuse';
export const BTN_RESCIND = 'Rescind';
export const BTN_SAVE = 'Save';
export const BTN_SAVE_DRAFT = 'Save Draft';
export const BTN_SIGN_1_2 = 'Sign 1/2';
export const BTN_SIGN_2_2 = 'Sign 2/2';
export const BTN_YES = 'Yes';
