const NOTIFICATION_TYPES = {
  CREDIT_TRANSFER_APPROVED: 'Transfer Approved',
  CREDIT_TRANSFER_COMMENT: 'Transfer Comment Created Or Updated',
  CREDIT_TRANSFER_CREATED: 'Transfer Created',
  CREDIT_TRANSFER_DECLINED: 'Transfer Declined',
  CREDIT_TRANSFER_INTERNAL_COMMENT: 'Transfer Internal Comment Created Or Updated',
  CREDIT_TRANSFER_PROPOSAL_ACCEPTED: 'Transfer Signed',
  CREDIT_TRANSFER_PROPOSAL_REFUSED: 'Transfer Refused',
  CREDIT_TRANSFER_RECOMMENDED_FOR_APPROVAL: 'Transfer Recommended For Approval',
  CREDIT_TRANSFER_RECOMMENDED_FOR_DECLINATION: 'Transfer Not Recommended For Approval',
  CREDIT_TRANSFER_RESCINDED: 'Transfer Rescinded',
  CREDIT_TRANSFER_SIGNED_1OF2: 'Transfer Proposed',
  CREDIT_TRANSFER_SIGNED_2OF2: 'Transfer Signed',
  PVR_APPROVED: 'PVR Approved',
  PVR_COMMENT: 'PVR Comment Created Or Updated',
  PVR_CREATED: 'PVR Created',
  PVR_DECLINED: 'PVR Declined',
  PVR_INTERNAL_COMMENT: 'PVR Internal Comment Created Or Updated',
  PVR_PULLED_BACK: 'PVR Recalled as draft',
  PVR_RECOMMENDED_FOR_APPROVAL: 'PVR Recommended For Approval',
  PVR_RETURNED_TO_ANALYST: 'PVR Returned to Analyst',
  DOCUMENT_ARCHIVED: 'Submission Archived',
  DOCUMENT_PENDING_SUBMISSION: 'File Pending Submission',
  DOCUMENT_RECEIVED: 'Submission Received',
  DOCUMENT_SUBMITTED: 'File Submitted',
  DOCUMENT_SCAN_FAILED: 'File Security Scan Failed',
  COMPLIANCE_REPORT_DRAFT: 'Compliance Report Draft Saved',
  COMPLIANCE_REPORT_SUBMITTED: 'Compliance Report Submitted',
  COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST: 'Compliance Report Recommended for Acceptance - Analyst',
  COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST: 'Compliance Report Recommended for Rejection - Analyst',
  COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER: 'Compliance Report Recommended for Acceptance - Manager',
  COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER: 'Compliance Report Recommended for Rejection - Manager',
  COMPLIANCE_REPORT_ACCEPTED: 'Compliance Report Accepted',
  COMPLIANCE_REPORT_REJECTED: 'Compliance Report Rejected',
  COMPLIANCE_REPORT_REQUESTED_SUPPLEMENTAL: 'Compliance Report Supplemental Requested',
  EXCLUSION_REPORT_DRAFT: 'Exclusion Report Draft Saved',
  EXCLUSION_REPORT_SUBMITTED: 'Exclusion Report Submitted',
  EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST: 'Exclusion Report Recommended for Acceptance - Analyst',
  EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST: 'Exclusion Report Recommended for Rejection - Analyst',
  EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER: 'Exclusion Report Recommended for Acceptance - Manager',
  EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER: 'Exclusion Report Recommended for Rejection - Manager',
  EXCLUSION_REPORT_ACCEPTED: 'Exclusion Report Accepted',
  EXCLUSION_REPORT_REJECTED: 'Exclusion Report Rejected',
  EXCLUSION_REPORT_REQUESTED_SUPPLEMENTAL: 'Exclusion Report Supplemental Requested'
}

export default NOTIFICATION_TYPES
