export default {
  ERROR_CREDIT_TRANSFERS_HISTORY_REQUEST: 'ERROR_CREDIT_TRANSFERS_HISTORY_REQUEST',
  GET_CREDIT_TRANSFERS_HISTORY_REQUEST: 'GET_CREDIT_TRANSFERS_HISTORY_REQUEST',
  RECEIVE_CREDIT_TRANSFERS_HISTORY_REQUEST: 'RECEIVE_CREDIT_TRANSFERS_HISTORY_REQUEST'
};
