export default {
  ERROR_CREDIT_CALCULATION_REQUEST: 'ERROR_CREDIT_CALCULATION_REQUEST',
  GET_CREDIT_CALCULATION_REQUEST: 'GET_CREDIT_CALCULATION_REQUEST',
  RECEIVE_CREDIT_CALCULATION_REQUEST: 'RECEIVE_CREDIT_CALCULATION_REQUEST'
};
