export default {
  ADD_DOCUMENT_UPLOAD_REQUEST: 'ADD_DOCUMENT_UPLOAD_REQUEST',
  ERROR_ADD_DOCUMENT_UPLOAD: 'ERROR_ADD_DOCUMENT_UPLOAD',
  ERROR_DOCUMENT_UPLOAD_REQUEST: 'ERROR_DOCUMENT_UPLOAD_REQUEST',
  ERROR_DOCUMENT_UPLOADS_REQUEST: 'ERROR_DOCUMENT_UPLOADS_REQUEST',
  ERROR_UPDATE_DOCUMENT_UPLOAD: 'ERROR_UPDATE_DOCUMENT_UPLOAD',
  GET_DOCUMENT_UPLOAD_REQUEST: 'GET_DOCUMENT_UPLOAD_REQUEST',
  GET_DOCUMENT_UPLOADS_REQUEST: 'GET_DOCUMENT_UPLOADS_REQUEST',
  RECEIVE_DOCUMENT_UPLOAD_REQUEST: 'RECEIVE_DOCUMENT_UPLOAD_REQUEST',
  RECEIVE_DOCUMENT_UPLOADS_REQUEST: 'RECEIVE_DOCUMENT_UPLOADS_REQUEST',
  SUCCESS_ADD_DOCUMENT_UPLOAD: 'SUCCESS_ADD_DOCUMENT_UPLOAD',
  SUCCESS_UPDATE_DOCUMENT_UPLOAD: 'SUCCESS_UPDATE_DOCUMENT_UPLOAD',
  UPDATE_DOCUMENT_UPLOAD_REQUEST: 'UPDATE_DOCUMENT_UPLOAD_REQUEST'
};
