export default {
  ERROR_DOCUMENT_UPLOADS_REQUEST: 'ERROR_DOCUMENT_UPLOADS_REQUEST',
  GET_DOCUMENT_UPLOADS_REQUEST: 'GET_DOCUMENT_UPLOADS_REQUEST',
  RECEIVE_DOCUMENT_UPLOADS_REQUEST: 'RECEIVE_DOCUMENT_UPLOADS_REQUEST'
};
