export default {
  POST_CHANGE_NOTIFICATION_READ_STATUS: 'POST_CHANGE_NOTIFICATION_READ_STATUS',
  RECEIVE_CHANGE_NOTIFICATION_READ_STATUS: 'RECEIVE_CHANGE_NOTIFICATION_READ_STATUS'
  ERROR_NOTIFICATIONS_REQUEST: 'ERROR_NOTIFICATIONS_REQUEST',
  ERROR_SUBSCRIPTIONS_REQUEST: 'ERROR_SUBSCRIPTIONS_REQUEST',
  ERROR_UPDATE_SUBSCRIPTIONS_REQUEST: 'ERROR_UPDATE_SUBSCRIPTIONS_REQUEST',
  GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  GET_SUBSCRIPTIONS_REQUEST: 'GET_SUBSCRIPTIONS_REQUEST',
  RECEIVE_NOTIFICATIONS_REQUEST: 'RECEIVE_NOTIFICATIONS_REQUEST',
  RECEIVE_SUBSCRIPTIONS_REQUEST: 'RECEIVE_SUBSCRIPTIONS_REQUEST',
  SUCCESS_UPDATE_SUBSCRIPTIONS_REQUEST: 'SUCCESS_UPDATE_SUBSCRIPTIONS_REQUEST',
  UPDATE_SUBSCRIPTIONS_REQUEST: 'UPDATE_SUBSCRIPTIONS_REQUEST'
};
