export default {
  ERROR_NOTIFICATION_REQUEST: 'ERROR_NOTIFICATION_REQUEST',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  RECEIVE_NOTIFICATIONS_REQUEST: 'RECEIVE_NOTIFICATIONS_REQUEST',
  POST_CHANGE_NOTIFICATION_READ_STATUS: 'POST_CHANGE_NOTIFICATION_READ_STATUS',
  RECEIVE_CHANGE_NOTIFICATION_READ_STATUS: 'RECEIVE_CHANGE_NOTIFICATION_READ_STATUS'
};
