export default {
  ERROR_NOTIFICATIONS_REQUEST: 'ERROR_NOTIFICATIONS_REQUEST',
  ERROR_SUBSCRIPTIONS_REQUEST: 'ERROR_SUBSCRIPTIONS_REQUEST',
  ERROR_UPDATE_SUBSCRIPTIONS_REQUEST: 'ERROR_UPDATE_SUBSCRIPTIONS_REQUEST',
  GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  GET_SUBSCRIPTIONS_REQUEST: 'GET_SUBSCRIPTIONS_REQUEST',
  RECEIVE_NOTIFICATIONS_REQUEST: 'RECEIVE_NOTIFICATIONS_REQUEST',
  RECEIVE_SUBSCRIPTIONS_REQUEST: 'RECEIVE_SUBSCRIPTIONS_REQUEST',
  SUCCESS_UPDATE_SUBSCRIPTIONS_REQUEST: 'SUCCESS_UPDATE_SUBSCRIPTIONS_REQUEST',
  UPDATE_SUBSCRIPTIONS_REQUEST: 'UPDATE_SUBSCRIPTIONS_REQUEST'
};
