export default {
  ERROR_FUEL_SUPPLIERS_REQUEST: 'ERROR_FUEL_SUPPLIERS_REQUEST',
  ERROR_ORGANIZATION_REQUEST: 'ERROR_ORGANIZATION_REQUEST',
  ERROR_ORGANIZATIONS_REQUEST: 'ERROR_ORGANIZATIONS_REQUEST',
  GET_FUEL_SUPPLIERS_REQUEST: 'GET_FUEL_SUPPLIERS_REQUEST',
  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_ORGANIZATION_REQUEST: 'GET_ORGANIZATION_REQUEST',
  GET_ORGANIZATIONS_REQUEST: 'GET_ORGANIZATIONS_REQUEST',
  SEARCH_ORGANIZATIONS_REQUEST: 'SEARCH_ORGANIZATIONS_REQUEST',
  RECEIVE_FUEL_SUPPLIERS_REQUEST: 'RECEIVE_FUEL_SUPPLIERS_REQUEST',
  RECEIVE_MEMBERS_REQUEST: 'RECEIVE_MEMBERS_REQUEST',
  RECEIVE_ORGANIZATIONS_REQUEST: 'RECEIVE_ORGANIZATIONS_REQUEST'
};
