export default {
  ERROR_ROLE_REQUEST: 'ERROR_ROLE_REQUEST',
  ERROR_ROLES_REQUEST: 'ERROR_ROLES_REQUEST',
  GET_ROLE_REQUEST: 'GET_ROLE_REQUEST',
  GET_ROLES_REQUEST: 'GET_ROLES_REQUEST',
  RECEIVE_ROLE_REQUEST: 'RECEIVE_ROLE_REQUEST',
  RECEIVE_ROLES_REQUEST: 'RECEIVE_ROLES_REQUEST'
};
