export default {
  ERROR_SIGNING_AUTHORITY_ASSERTIONS_REQUEST: 'ERROR_SIGNING_AUTHORITY_ASSERTIONS_REQUEST',
  GET_SIGNING_AUTHORITY_ASSERTIONS_REQUEST: 'GET_SIGNING_AUTHORITY_ASSERTIONS_REQUEST',
  RECEIVE_SIGNING_AUTHORITY_ASSERTIONS_REQUEST: 'RECEIVE_SIGNING_AUTHORITY_ASSERTIONS_REQUEST'
};
