export default {
  ERROR_USER_REQUEST: 'ERROR_USER_REQUEST',
  GET_LOGGED_IN_USER: 'GET_LOGGED_IN_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  RECEIVE_USER_REQUEST: 'RECEIVE_USER_REQUEST'
};
