const SCHEDULE_A = {
  LEGAL_NAME: 1,
  POSTAL_ADDRESS: 2,
  FUEL_CLASS: 3,
  TRANSFER_TYPE: 4,
  QUANTITY: 5
};

const SCHEDULE_B = {
  FUEL_TYPE: 1,
  FUEL_CLASS: 2,
  PROVISION_OF_THE_ACT: 3,
  FUEL_CODE: 4,
  QUANTITY: 5,
  UNITS: 6,
  CARBON_INTENSITY_LIMIT: 7,
  CARBON_INTENSITY_FUEL: 8,
  ENERGY_DENSITY: 9,
  EER: 10,
  ENERGY_CONTENT: 11,
  CREDIT: 12,
  DEBIT: 13
};

const SCHEDULE_C = {
  FUEL_TYPE: 1,
  FUEL_CLASS: 2,
  QUANTITY: 3,
  UNITS: 4,
  EXPECTED_USE: 5,
  EXPECTED_USE_OTHER: 6
};

const SCHEDULE_D = {
  WORKSHEET_NAME: 1,
  CELL: 2,
  VALUE: 3,
  UNITS: 4,
  DESCRIPTION: 5
};

const SCHEDULE_D_INPUT = {
  FUEL_TYPE: 0,
  FEEDSTOCK: 1,
  FUEL_CLASS: 2
};

const SCHEDULE_D_OUTPUT = {
  FUEL_DISPENSING: 0,
  FUEL_DISTRIBUTION: 1,
  FUEL_PRODUCTION: 2,
  FEEDSTOCK_TRANSMISSION: 3,
  FEEDSTOCK_RECOVERY: 4,
  FEEDSTOCK_UPGRADING: 5,
  LAND_USE_CHANGE: 6,
  FERTILIZER_MANUFACTURE: 7,
  GAS_LEAKS_AND_FUELS: 8,
  CO2_AND_H2S_REMOVED: 9,
  EMISSIONS_DISPLACED: 10,
  FUEL_USE: 11,
  TOTAL: 12,
  CARBON_INTENSITY: 13
};

export { SCHEDULE_A, SCHEDULE_B, SCHEDULE_C, SCHEDULE_D, SCHEDULE_D_INPUT, SCHEDULE_D_OUTPUT };
