const COMPLIANCE_REPORT = {
  ANALYST_RECOMMEND_ACCEPTANCE: 'ANALYST_RECOMMEND_ACCEPTANCE_COMPLIANCE_REPORT',
  ANALYST_RECOMMEND_REJECTION: 'ANALYST_RECOMMEND_REJECTION_COMPLIANCE_REPORT',
  MANAGE: 'COMPLIANCE_REPORT_MANAGE',
  MANAGER_RECOMMEND_ACCEPTANCE: 'MANAGER_RECOMMEND_ACCEPTANCE_COMPLIANCE_REPORT',
  MANAGER_RECOMMEND_REJECTION: 'MANAGER_RECOMMEND_REJECTION_COMPLIANCE_REPORT',
  SIGN: 'SIGN_COMPLIANCE_REPORT',
  VIEW: 'VIEW_COMPLIANCE_REPORT'
};

export default COMPLIANCE_REPORT;
