const CREDIT_TRANSACTIONS = {
  APPROVE: 'APPROVE_CREDIT_TRANSFER',
  PROPOSE: 'PROPOSE_CREDIT_TRANSFER',
  SIGN: 'SIGN_CREDIT_TRANSFER',
  USE_HISTORICAL_DATA_ENTRY: 'USE_HISTORICAL_DATA_ENTRY',
  VIEW: 'VIEW_CREDIT_TRANSFERS'
};

export default CREDIT_TRANSACTIONS;
