{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "spilo.fullname" . }}-intra-release
  labels: {{ include "spilo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "spilo.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels: {{ include "spilo.selectorLabels" . | nindent 10 }}
{{- end }}
