{{- if not .Values.credentials.useExistingSecret }}
{{- $superuserPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $adminPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $standbyPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "spilo.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $superuserPassword = index $secret.data "password-superuser" }}
{{- $adminPassword = index $secret.data "password-admin" }}
{{- $standbyPassword = index $secret.data "password-standby" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spilo.fullname" . }}
  labels: {{ include "spilo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.credentials.random }}
  password-superuser: {{ $superuserPassword }}
  password-admin: {{ $adminPassword }}
  password-standby: {{ $standbyPassword }}
  {{- else }}
  password-superuser: {{ .Values.credentials.superuser | b64enc }}
  password-admin: {{ .Values.credentials.admin | b64enc }}
  password-standby: {{ .Values.credentials.standby | b64enc }}
  {{- end }}
{{- end }}