apiVersion: v1
kind: Service
metadata:
  name: {{ template "spilo.fullname" . }}
  labels: {{ include "spilo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector: {{ include "spilo.selectorLabels" . | nindent 4 }}
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "spilo.fullname" . }}-readonly
  labels: {{ include "spilo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector: {{ include "spilo.selectorLabels" . | nindent 4 }}
    spilo-role: replica
