{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spilo.serviceAccountName" . }}
  labels: {{ include "spilo.labels" . | nindent 4 }}
{{- end }}
