# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170817_2124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audit',
            table='AUDIT',
        ),
        migrations.AlterModelTable(
            name='credittrade',
            table='CREDIT_TRADE',
        ),
        migrations.AlterModelTable(
            name='credittradehistory',
            table='CREDIT_TRADE_HISTORY',
        ),
        migrations.AlterModelTable(
            name='credittradestatus',
            table='CREDIT_TRADE_STATUS',
        ),
        migrations.AlterModelTable(
            name='credittradetype',
            table='CREDIT_TRADE_TYPE',
        ),
        migrations.AlterModelTable(
            name='fuelsupplier',
            table='FUEL_SUPPLIER',
        ),
        migrations.AlterModelTable(
            name='fuelsupplieractionstype',
            table='FUEL_SUPPLIER_ACTIONS_TYPE',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierattachment',
            table='FUEL_SUPPLIER_ATTACHMENT',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierattachmenttag',
            table='FUEL_SUPPLIER_ATTACHMENT_TAG',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierbalance',
            table='FUEL_SUPPLIER_BALANCE',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierccdata',
            table='FUEL_SUPPLIER_C_C_DATA',
        ),
        migrations.AlterModelTable(
            name='fuelsuppliercontact',
            table='FUEL_SUPPLIER_CONTACT',
        ),
        migrations.AlterModelTable(
            name='fuelsuppliercontactrole',
            table='FUEL_SUPPLIER_CONTACT_ROLE',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierhistory',
            table='FUEL_SUPPLIER_HISTORY',
        ),
        migrations.AlterModelTable(
            name='fuelsupplierstatus',
            table='FUEL_SUPPLIER_STATUS',
        ),
        migrations.AlterModelTable(
            name='fuelsuppliertype',
            table='FUEL_SUPPLIER_TYPE',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='NOTIFICATION',
        ),
        migrations.AlterModelTable(
            name='notificationevent',
            table='NOTIFICATION_EVENT',
        ),
        migrations.AlterModelTable(
            name='notificationtype',
            table='NOTIFICATION_TYPE',
        ),
        migrations.AlterModelTable(
            name='opportunity',
            table='OPPORTUNITY',
        ),
        migrations.AlterModelTable(
            name='opportunityhistory',
            table='OPPORTUNITY_HISTORY',
        ),
        migrations.AlterModelTable(
            name='opportunitystatus',
            table='OPPORTUNITY_STATUS',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='PERMISSION',
        ),
        migrations.AlterModelTable(
            name='role',
            table='ROLE',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='ROLE_PERMISSION',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
        migrations.AlterModelTable(
            name='userfavourite',
            table='USER_FAVOURITE',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='USER_ROLE',
        ),
    ]
