# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20171016_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittradehistory',
            name='creditTradeUpdateTime',
            field=models.DateTimeField(),
        ),
    ]
