# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20171102_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittrade',
            old_name='fairMarketValuePerCredit',
            new_name='fairMarketValuePerCreditRemove',
        ),
        migrations.RenameField(
            model_name='credittradehistory',
            old_name='newFairMarketValuePerCredit',
            new_name='newFairMarketValuePerCreditRemove',
        ),
        migrations.RenameField(
            model_name='credittrade',
            old_name='fairMarketValuePerCreditDecimal',
            new_name='fairMarketValuePerCredit',
        ),
        migrations.RenameField(
            model_name='credittradehistory',
            old_name='newFairMarketValuePerCreditDecimal',
            new_name='newFairMarketValuePerCredit',
        ),
        migrations.RemoveField(
            model_name='credittrade',
            name='fairMarketValuePerCreditRemove',
        ),
        migrations.RemoveField(
            model_name='credittradehistory',
            name='newFairMarketValuePerCreditRemove',
        ),
    ]
