apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: nginx-runtime
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: nginx-runtime
    name: nginx-runtime
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nginx-runtime:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: openshift/templates/nginx-runtime
      git:
        ref: master
        uri: https://github.com/bcgov/tfrs.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
  status:
    lastVersion: 0
