---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: notification-server-bc
  creationTimestamp:
parameters:
- name: NAME
  displayName:
  description: the module name entered when run yo bcdk:pipeline, which is tfrs
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: GIT_URL
  displayName:
  description: tfrs repo
  required: true
- name: GIT_REF
  displayName:
  description: tfrs ref
  required: true  
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the celery image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-notification-server
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: "" 
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${NAME}-notification-server${SUFFIX}
    creationTimestamp:
  spec:
    triggers: []
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
      contextDir: frontend
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-16:1-71
        forcePull: true
        noCache: true   
        env:
          - name: ARTIFACTORY_USER
            valueFrom:
              secretKeyRef:
                name: artifacts-tfrs-artifactory-service-account-wofwpt
                key: username
          - name: ARTIFACTORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: artifacts-tfrs-artifactory-service-account-wofwpt
                key: password  
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-notification-server:${VERSION}
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 2Gi
    postCommit: {}
    nodeSelector:
    failedBuildsHistoryLimit: 5
  status:
    lastVersion: 0
