---
## This build config is not being used.
kind: Template
apiVersion: v1
metadata:
  name: rabbitmq-bc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    required: true
  - name: GIT_URL
    displayName: tfrs Git Repo URL
    description: The URL to your GIT repo
    required: true
    value: https://github.com/bcgov/tfrs.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the rabbitmq image
      creationTimestamp: null
      name: rabbitmq
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: rabbitmq-${ENV_NAME}
      creationTimestamp:
    spec:
      triggers: []
      runPolicy: SerialLatestOnly
      source:
        contextDir: openshift/templates/rabbitmq/docker
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-${ENV_NAME}
                  key: ADMIN_PASSWORD
            - name: TFRS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-${ENV_NAME}
                  key: TFRS_PASSWORD
          forcePull: false
          noCache: true
          imageOptimizationPolicy: SkipLayers
      output:
        to:
          kind: ImageStreamTag
          name: rabbitmq:3.8.3-management-${ENV_NAME}
      resources: {}
      postCommit: {}
      nodeSelector:
    status:
      lastVersion: 0
