apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: ADMIN_PASSWORD
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  required: true
- name: ZEVA_PASSWORD
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: zeva-rabbitmq
  stringData:
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ZEVA_PASSWORD: ${ZEVA_PASSWORD}
  type: Opaque