---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tfrs-dc
  creationTimestamp: 
labels:
  template: tfrs-backend-template
parameters:
- name: ENV_NAME
  displayName: Environment name
  description: 'Sample values: dev, test and prod'
  required: true
- name: SOURCE_IS_NAME
  displayName: The source image stream name
  description: 'The image stream could trigger the deployment, sample values: tfrs-develop
    and tfrs'
  required: true
- name: KEYCLOAK_SA_BASEURL
  displayName: KEYCLOAK_SA_BASEURL
  description: 'Valid values: https://dev.oidc.gov.bc.ca, https://test.oidc.gov.bc.ca,
    https://oidc.gov.bc.ca'
  required: true
- name: KEYCLOAK_SA_CLIENT_ID
  displayName: KEYCLOAK_SA_CLIENT_ID
  description: 'Valid values: tfrs-dev-django-sa, tfrs-django-sa, tfrs-django-sa'
  required: true
- name: KEYCLOAK_SA_REALM
  displayName: KEYCLOAK_SA_REALM
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_AUDIENCE
  displayName: KEYCLOAK_AUDIENCE
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_CERTS_URL
  displayName: KEYCLOAK_CERTS_URL
  description: 'Valid values: https://dev.oidc.gov.bc.ca/auth/realms/tfrs-dev/protocol/openid-connect/certs,
    https://test.oidc.gov.bc.ca/auth/realms/tfrs/protocol/openid-connect/certs, https://oidc.gov.bc.ca/auth/realms/tfrs/protocol/openid-connect/certs'
  required: true
- name: KEYCLOAK_CLIENT_ID
  displayName: KEYCLOAK_CLIENT_ID
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_ISSUER
  displayName: KEYCLOAK_ISSUER
  description: 'Valid values: https://dev.oidc.gov.bc.ca/auth/realms/tfrs-dev, https://test.oidc.gov.bc.ca/auth/realms/tfrs,
    https://oidc.gov.bc.ca/auth/realms/tfrs'
  required: true
- name: KEYCLOAK_REALM
  displayName: KEYCLOAK_REALM
  description: 'Valid values: https://dev.oidc.gov.bc.ca/auth/realms/tfrs-dev, https://test.oidc.gov.bc.ca/auth/realms/tfrs,
    https://oidc.gov.bc.ca/auth/realms/tfrs'
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
- name: DATABASE_SERVICE_NAME
  displayName: database service name
  description: database service name
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the client / frontend image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-backend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${NAME}-backend${SUFFIX}
    generation: 1
    creationTimestamp: 
    labels:
      template: tfrs-app-environment
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
        mid:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sh"
            - "-c"
            - python manage.py migrate;
            containerName: tfrs-app
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - tfrs-app
        from:
          kind: ImageStreamTag
          name: ${NAME}-backend:${VERSION}
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      name: ${NAME}-backend${SUFFIX}
    template:
      metadata:
        name: ${NAME}-backend${SUFFIX}
        creationTimestamp: 
        labels:
          name: tfrs
      spec:
        containers:
        - name: tfrs-app
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: KEYCLOAK_SA_BASEURL
            value: "${KEYCLOAK_SA_BASEURL}"
          - name: KEYCLOAK_SA_CLIENT_ID
            value: "${KEYCLOAK_SA_CLIENT_ID}"
          - name: KEYCLOAK_SA_REALM
            value: "${KEYCLOAK_SA_REALM}"
          - name: KEYCLOAK_AUDIENCE
            value: "${KEYCLOAK_AUDIENCE}"
          - name: KEYCLOAK_CERTS_URL
            value: "${KEYCLOAK_CERTS_URL}"
          - name: KEYCLOAK_CLIENT_ID
            value: "${KEYCLOAK_CLIENT_ID}"
          - name: KEYCLOAK_ENABLED
            value: 'true'
          - name: KEYCLOAK_ISSUER
            value: "${KEYCLOAK_ISSUER}"
          - name: KEYCLOAK_REALM
            value: "${KEYCLOAK_REALM}"
          - name: KEYCLOAK_SA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-sa-client-secret
                key: KEYCLOAK_SA_CLIENT_SECRET
          - name: AMQP_HOST
            value: rabbit.mem-tfrs-${ENV_NAME}.svc
          - name: AMQP_USER
            value: tfrs
          - name: AMQP_VHOST
            value: "/tfrs"
          - name: BYPASS_CLAMAV
            value: 'false'
          - name: EMAIL_FROM_ADDRESS
            value: donotreply@gov.bc.ca
          - name: EMAIL_SENDING_ENABLED
            value: 'true'
          - name: MINIO_BUCKET_NAME
            value: tfrs
          - name: SMTP_SERVER_HOST
            value: apps.smtp.gov.bc.ca
          - name: DATABASE_SERVICE_NAME
            value: patroni-master${SUFFIX}
          - name: DATABASE_ENGINE
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: patroni-${SUFFIX}
                key: app-db-name
          - name: APP_CONFIG
            value: "/opt/app-root/src/gunicorn.cfg"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: patroni-${SUFFIX}
                key: app-db-username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: patroni-${SUFFIX}
                key: app-db-password
          - name: RABBITMQ_USER
            value: tfrs
          - name: RABBITMQ_VHOST
            value: "/tfrs"
          - name: RABBITMQ_HOST
            value: rabbit.mem-tfrs-${ENV_NAME}.svc
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-tfrs
                key: TFRS_PASSWORD
          - name: MINIO_ENDPOINT
            value: docs-mem-tfrs-${ENV_NAME}.pathfinder.gov.bc.ca:443
          - name: MINIO_USE_SSL
            value: 'true'
          - name: DOCUMENTS_API_ENABLED
            value: 'true'
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minioSecretKey
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-tfrs
                key: TFRS_PASSWORD
          - name: CLAMAV_HOST
            value: rabbit.mem-tfrs-${ENV_NAME}.svc
          - name: FUEL_CODES_API_ENABLED
            value: 'true'
          - name: CREDIT_CALCULATION_API_ENABLED
            value: 'true'
          - name: COMPLIANCE_REPORTING_API_ENABLED
            value: 'true'
          - name: EXCLUSION_REPORTS_API_ENABLED
            value: 'true'
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-key
                key: DJANGO_SECRET_KEY
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
