---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tfrs-dc
  creationTimestamp:
labels:
  template: tfrs-backend-template
parameters:
- name: NAME
  displayName: App name
  description: App name
  value: tfrs
  required: true
- name: SUFFIX
  displayName: suffix
  description: such as -dev-1696, -dev ane etc.
  required: true  
- name: ENV_NAME
  displayName: environment name
  description: such as dev, test and prod
  required: true    
- name: NAMESPACE
  displayName: Environment name
  description: 'Sample values: 0ab226-dev, 0ab226-test and 0ab226-prod'
  required: true
- name: VERSION
  displayName: null
  description: image tag name for output
  required: true  
- name: KEYCLOAK_SA_BASEURL
  displayName: KEYCLOAK_SA_BASEURL
  required: true
- name: KEYCLOAK_SA_CLIENT_ID
  displayName: KEYCLOAK_SA_CLIENT_ID
  required: true
- name: KEYCLOAK_SA_REALM
  displayName: KEYCLOAK_SA_REALM
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_AUDIENCE
  displayName: KEYCLOAK_AUDIENCE
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_CERTS_URL
  displayName: KEYCLOAK_CERTS_URL
  required: true
- name: KEYCLOAK_CLIENT_ID
  displayName: KEYCLOAK_CLIENT_ID
  description: 'Valid values: tfrs-dev, tfrs, tfrs'
  required: true
- name: KEYCLOAK_ISSUER
  displayName: KEYCLOAK_ISSUER
  required: true
- name: KEYCLOAK_REALM
  displayName: KEYCLOAK_REALM
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
- name: REPLICAS
  displayName: replicas
  description: replicas
  required: true
- name: DB_SERVICE_NAME
  displayName: The database service name
  description: The database service name
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the backend image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-backend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${NAME}-backend${SUFFIX}
    creationTimestamp: null
    labels:
      name: ${NAME}-backend${SUFFIX}
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
        mid:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sh"
            - "-c"
            - python manage.py migrate;
            containerName: tfrs-app
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - tfrs-app
        from:
          kind: ImageStreamTag
          name: ${NAME}-backend:${VERSION}
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: ${{REPLICAS}}
    test: false
    selector:
      name: ${NAME}-backend${SUFFIX}
    template:
      metadata:
        name: ${NAME}-backend${SUFFIX}
        creationTimestamp:
        labels:
          name: ${NAME}-backend${SUFFIX}
      spec:
        containers:
        - name: tfrs-app
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: KEYCLOAK_SA_BASEURL
            value: ${KEYCLOAK_SA_BASEURL}
          - name: KEYCLOAK_SA_CLIENT_ID
            value: ${KEYCLOAK_SA_CLIENT_ID}
          - name: KEYCLOAK_SA_REALM
            value: ${KEYCLOAK_SA_REALM}
          - name: KEYCLOAK_AUDIENCE
            value: ${KEYCLOAK_AUDIENCE}
          - name: KEYCLOAK_CERTS_URL
            value: ${KEYCLOAK_CERTS_URL}
          - name: KEYCLOAK_CLIENT_ID
            value: ${KEYCLOAK_CLIENT_ID}
          - name: KEYCLOAK_ENABLED
            value: 'true'
          - name: KEYCLOAK_ISSUER
            value: ${KEYCLOAK_ISSUER}
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}
          - name: KEYCLOAK_SA_CLIENT_SECRET
            value: notbeingused
          - name: EMAIL_FROM_ADDRESS
            value: donotreply@gov.bc.ca
          - name: EMAIL_SENDING_ENABLED
            value: 'true'
          - name: MINIO_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: tfrs-object-storage
                key: BUCKET
          - name: SMTP_SERVER_HOST
            value: apps.smtp.gov.bc.ca
          - name: SMTP_SERVER_PORT
            value: '2500'
          - name: DATABASE_SERVICE_NAME
            value: ${DB_SERVICE_NAME}
          - name: DATABASE_ENGINE
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: tfrs-patroni-app
                key: app-db-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: tfrs-patroni-app
                key: app-db-username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tfrs-patroni-app
                key: app-db-password
          - name: POSTGRESQL_SERVICE_HOST
            value: tfrs-spilo.${NAMESPACE}.svc.cluster.local
          - name: POSTGRESQL_SERVICE_PORT
            value: '5432'
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: tfrs-rabbitmq-app
                key: username
          - name: RABBITMQ_VHOST
            value: "tfrs-vhost"
          - name: RABBITMQ_HOST
            value: tfrs-rabbitmq.${NAMESPACE}.svc.cluster.local
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tfrs-rabbitmq-app
                key: password
          - name: RABBITMQ_PORT
            value: '5672'
          - name: MINIO_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: tfrs-object-storage
                key: ENDPOINT
          - name: MINIO_USE_SSL
            value: 'true'
          - name: DOCUMENTS_API_ENABLED
            value: 'true'
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: tfrs-object-storage
                key: USER_ID
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: tfrs-object-storage
                key: KEY
          - name: FUEL_CODES_API_ENABLED
            value: 'true'
          - name: CREDIT_CALCULATION_API_ENABLED
            value: 'true'
          - name: COMPLIANCE_REPORTING_API_ENABLED
            value: 'true'
          - name: EXCLUSION_REPORTS_API_ENABLED
            value: 'true'
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-key
                key: DJANGO_SECRET_KEY
          - name: APP_CONFIG
            value: "/opt/app-root/src/gunicorn.cfg.py"
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
