---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: scan-handler-dc
  creationTimestamp:
parameters:
- name: ENV_NAME
  displayName: Environment name
  description: 'Sample values: dev, test and prod'
  required: true
- name: SOURCE_IS_NAME
  displayName: The source image stream name
  description: 'The image stream could trigger the deployment, sample values: scan-handler-develop
    and scan-handler'
  required: true
- name: DATABASE_SERVICE_NAME
  displayName: database service name
  description: database service name
  required: true
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: scan-handler
    generation: 90
    creationTimestamp:
    labels:
      app: scan-handler
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - scan-handler
        from:
          kind: ImageStreamTag
          namespace: mem-tfrs-tools
          name: "${SOURCE_IS_NAME}:${ENV_NAME}"
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: scan-handler
      deploymentconfig: scan-handler
    template:
      metadata:
        creationTimestamp:
        labels:
          app: scan-handler
          deploymentconfig: scan-handler
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
        - name: scan-handler
          image: ''
          env:
          - name: RABBITMQ_VHOST
            value: "/tfrs"
          - name: RABBITMQ_USER
            value: tfrs
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-tfrs
                key: TFRS_PASSWORD
          - name: RABBITMQ_HOST
            value: rabbit.mem-tfrs-${ENV_NAME}.svc
          - name: RABBITMQ_PORT
            value: '5672'
          - name: DATABASE_SERVICE_NAME
            value: "${DATABASE_SERVICE_NAME}"
          - name: DATABASE_ENGINE
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: patroni-${ENV_NAME}
                key: app-db-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: patroni-${ENV_NAME}
                key: app-db-username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: patroni-${ENV_NAME}
                key: app-db-password
          resources:
            limits:
              cpu: 250m
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
