---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: scan-handler-dc
  creationTimestamp:
parameters:
- name: NAME
  displayName: App name
  description: App name
  value: tfrs
  required: true
- name: SUFFIX
  displayName: suffix
  description: such as -dev-1696, -dev ane etc.
  required: true  
- name: NAMESPACE
  displayName: Environment name
  description: 'Sample values: 0ab226-dev, 0ab226-test and 0ab226-prod'
  required: true
- name: VERSION
  displayName: null
  description: image tag name for output
  required: true
- description: Starting amount of CPU the container can use.
  displayName: CPU REQUEST
  name: CPU_REQUEST
  value: '100m'
  required: true
- description: Maximum amount of CPU the container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  value: '250m'
  required: true
- description: Starting amount of memory the container can use.
  displayName: Memory Request
  name: MEMORY_REQUEST
  value: 256Mi
  required: true
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi    
  required: true  
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the scan handler image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-scan-handler
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${NAME}-scan-handler${SUFFIX}
    creationTimestamp:
    labels:
      name: ${NAME}-scan-handler${SUFFIX}
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - scan-handler
        from:
          kind: ImageStreamTag
          name: ${NAME}-scan-handler:${VERSION}
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      name: ${NAME}-scan-handler${SUFFIX}
    template:
      metadata:
        creationTimestamp:
        labels:
          name: ${NAME}-scan-handler${SUFFIX}
      spec:
        containers:
        - name: scan-handler
          image: ''
          env:
          - name: RABBITMQ_VHOST
            value: "/tfrs"
          - name: RABBITMQ_USER
            value: tfrs
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}${SUFFIX}-rabbitmq-cluster-secret
                key: tfrs_password
          - name: RABBITMQ_HOST
            value: ${NAME}${SUFFIX}-rabbitmq-cluster.${NAMESPACE}.svc.cluster.local
          - name: RABBITMQ_PORT
            value: '5672'
          - name: DATABASE_SERVICE_NAME
            value: patroni-master${SUFFIX}
          - name: DATABASE_ENGINE
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: patroni${SUFFIX}
                key: app-db-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: patroni${SUFFIX}
                key: app-db-username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: patroni${SUFFIX}
                key: app-db-password
          resources:
            limits:
              cpu: 250m
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
