---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: scan-handler-bc
  creationTimestamp:
parameters:
- name: NAME
  displayName:
  description: the module name entered when run yo bcdk:pipeline, which is tfrs
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: GIT_URL
  displayName:
  description: tfrs repo
  required: true
- name: GIT_REF
  displayName:
  description: tfrs repo ref
  required: true      
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the celery image
    labels:
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-scan-handler
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: "" 
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${NAME}-scan-handler${SUFFIX}
    creationTimestamp:
  spec:
    triggers: []
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}   
    strategy:   
      type: Docker
      dockerStrategy:
        dockerfilePath: openshift-v4/templates/scan-handler/Dockerfile
        pullSecret:
          name: artifacts-pull-default-mogbga
        noCache: true
        forcePull: true
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-scan-handler:${VERSION}
    resources: 
      limits:
          cpu: 1500m
          memory: 1300Mi
      requests:
          cpu: 750m
          memory: 650Mi        
    postCommit: {}
    nodeSelector:
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
  status:
    lastVersion: 0
