# Default values for tfrs-notification-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 240Mi
  requests:
    cpu: 100m
    memory: 120Mi

route:
  createNotificationServerRoute: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

keycloak:
  certsUrl: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs