---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: tfrs-network-policy
metadata:
  name: allow-backend-accepts
parameters:
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-backend-accepts-${ENVIRONMENT}
    spec:
      podSelector:
        matchLabels:
          name: tfrs-backend-${ENVIRONMENT}
      ingress:
        - ports:
            - protocol: TCP
              port: 8080
          from:
            - podSelector:
                matchLabels:
                  name: tfrs-frontend-${ENVIRONMENT}
        - ports:
            - protocol: TCP
              port: 8080
          from:
            - namespaceSelector:
                matchLabels:
                  environment: ${ENVIRONMENT}
                  name: d2bd59
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: lcfs-backend-${ENVIRONMENT}
      policyTypes:
        - Ingress
    status: {}
