---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: tfrs-spilo-network-policy
metadata:
  name: tfrs-spilo-network-policy
parameters:
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-tfrs-spilo-accepts-${ENVIRONMENT}
    spec:
      ## Allow tfrs-spilo to accept communications from backend
      ## Allow tfrs-spilo to accept communications from backend-mid
      ## Allow tfrs-spilo to accept communications from scan-handler
      ## Allow tfrs-spilo to accept communications from schema-public
      ## Allow tfrs-spilo to accept communications from schema-audit
      ## Allow tfrs-spilo to accept communications from celery
      ## Allow tfrs-spilo to accept communications from nagios
      ## Allow tfrs-spilo to accept communications from backup-container
      ## Allow tfrs-spilo to accept communications from metabase from cthub
      ## Allow tfrs-spilo to accept communications from cron backup
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: tfrs-spilo
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-backend-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432       
        - from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-mid
          ports:
            - protocol: TCP
              port: 5432              
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-scan-handler-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432      
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-schema-spy-public-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-schema-spy-audit-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432    
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-celery-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432     
        - from:
            - podSelector:
                matchLabels:
                  app: nagios
          ports:
            - protocol: TCP
              port: 5432                             
        - from:
            - podSelector:
                matchLabels:
                  name: patroni-backup
          ports:
            - protocol: TCP
              port: 5432
        - from:
            - podSelector:
                matchLabels:
                  cronjob: tfrs-db-backup
          ports:
            - protocol: TCP
              port: 5432
        - from:
            - namespaceSelector:
                matchLabels:
                  name: 30b186
                  environment: ${ENVIRONMENT}
            - podSelector:
                matchLabels:
                  app: metabase
          ports:
            - protocol: TCP
              port: 5432     
