---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: tfrs-network-policy
metadata:
  name: tfrs-network-policy
parameters:
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-tfrs-rabbitmq-accepts-${ENVIRONMENT}
    spec:
      ## Allow rabbitmq to accept communications from notification server
      ## Allow rabbitmq to accept communications from backend
      ## Allow rabbitmq to accept communications from scan handler
      ## Allow rabbitmq to accept communications from scan coordinator
      ## Allow rabbitmq to accept communications from celery
      ## Allow rabbitmq to accept communications from other rabbitmq pods
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: tfrs-rabbitmq
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-notification-server-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5672          
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-backend-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5672            
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-scan-handler-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5672      
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-scan-coordinator-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5672   
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-celery-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5672           
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: tfrs-rabbitmq
          ports:
            - protocol: TCP
              port: 5672     
            - protocol: TCP
              port: 15672     
            - protocol: TCP
              port: 25672     
            - protocol: TCP
              port: 4369                                             
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-tfrs-clamav-accepts-${ENVIRONMENT}
    spec:
      ## Allow clamav to accept communications from scan coordinator
      ## Allow clamav to accept communications from backend
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: tfrs-clamav
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-scan-coordinator-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 3310     
        - from:
            - podSelector:
                matchLabels:
                  name: tfrs-backend-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 3310        

