---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: tfrs-network-policy
metadata:
  name: tfrs-network-policy
parameters:
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-minio-accepts-nagios
    spec:
      ## Allow minio to accept communication from nagios
      podSelector:
        matchLabels:
          app: tfrs-minio-${ENVIRONMENT}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: nagios
          ports:
            - protocol: TCP
              port: 9000                
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-cthub-metabase-${ENVIRONMENT}
    spec:
      ## Allow patroni to accept communications from cthub metabase
      podSelector:
        matchLabels:
          cluster-name: patroni-${ENVIRONMENT}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: 30b186
                  environment: ${ENVIRONMENT}
            - podSelector:
                matchLabels:
                  app: metabase
          ports:
            - protocol: TCP
              port: 5432                         
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-cthub-superset-${ENVIRONMENT}
    spec:
      ## Allow patroni to accept communications from cthub superset
      podSelector:
        matchLabels:
          cluster-name: patroni-${ENVIRONMENT}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: 30b186
                  environment: ${ENVIRONMENT}
            - podSelector:
                matchLabels:
                  app: superset
          ports:
            - protocol: TCP
              port: 5432                         
           
