kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: tfrs-scan-coordinator{{ .Values.suffix }}
  labels:
    {{- include "tfrs-scan-coordinator.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 300
    resources: {}
    activeDeadlineSeconds: 600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - scan-coordinator
        from:
          kind: ImageStreamTag
          name: tfrs-scan-coordinator:{{ .Values.scanCoordinatorImageTagName }}
    - type: ConfigChange
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  test: false
  selector:
    {{- include "tfrs-scan-coordinator.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "tfrs-scan-coordinator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: scan-coordinator
          env:
            - name: BYPASS_CLAMAV
              value: 'false'
            - name: CLAMAV_HOST
              value: tfrs-clamav.{{ .Values.namespace }}.svc.cluster.local
            - name: CLAMAV_PORT
              value: '3310'
            - name: AMQP_HOST
              value: tfrs-rabbitmq.{{ .Values.namespace }}.svc.cluster.local
            - name: AMQP_VHOST
              value: {{ .Values.rabbitmqVHost }}
            - name: AMQP_PORT
              value: '5672'
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-app
                  key: username
            - name: MINIO_ENDPOINT
              value: tfrs-minio-{{ .Values.envName }}.apps.silver.devops.gov.bc.ca
            - name: MINIO_USE_SSL
              value: 'true'
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tfrs-rabbitmq-app
                  key: password
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tfrs-minio-{{ .Values.envName }}
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tfrs-minio-{{ .Values.envName }}
                  key: MINIO_SECRET_KEY
          resources:
{{ toYaml .Values.resources | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
