apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: the password for tfrs user in rqbbitmq cluster
  name: tfrs-rabbitmq-app
parameters:
- description: The tfrs user 
  displayName: The tfrs user 
  name: USERNAME
  required: true
- description: The tfrs user password
  displayName: The tfrs user password
  name: PASSWORD
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: tfrs-rabbitmq-app
  stringData:
    username: ${USERNAME}
    password: ${PASSWORD}
