apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: schemaspy-bc
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: schema-spy
      buildconfig: schema-spy
    name: schema-spy
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: schema-spy:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/bcgov/SchemaSpy.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
