# Default values for tfrs-scan-coordinator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 60Mi
  requests:
    cpu: 50m
    memory: 30Mi