## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: TFRS release-2.0.0

on:
  push:
    branches: [ release-2.0.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  ## Also remember to update the version in .pipeline/lib/config.js
  PR_NUMBER: 1824
  RELEASE_NAME: release-2.0.0

jobs:

  ## This is the CI job
  build:

    name: Build TFRS on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Frontend Linting 
        continue-on-error: true
        run: |
          cd frontend
          pwd
          npm install
          npm run lint        

#      - name: Show current folder
#        continue-on-error: true
#        run: |
#          echo "show current folder as below:"
#          pwd     
#          ls -l
#          echo "show /github/workspace"
#          ls -l /github/workspace

#      - name: Backend Linting
#        uses: github/super-linter/slim@v4
#       continue-on-error: true
#        env:
#          VALIDATE_ALL_CODEBASE: false
#          DEFAULT_BRANCH: ${{ env.RELEASE_NAME }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          FILTER_REGEX_INCLUDE: .*backend/.*.py
#          VALIDATE_PYTHON: true

      ## Log in to Openshift with a token of service account
      - name: Log in to Openshift
        ##uses: redhat-actions/oc-login@v1   
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools

      ## Run build on Openshift
      - name: Run build
        run: |
          cd .pipeline
          npm install
          npm run build -- --pr=${{ env.PR_NUMBER }} --env=build 

  deploy-on-dev:

    name: Deploy TFRS on Dev
    runs-on: ubuntu-latest
    timeout-minutes: 240
    needs: build

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Openshift
        ##uses: redhat-actions/oc-login@v1
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools    

      - name: Run deploy
        run: |
          cd .pipeline
          npm install
          npm run deploy -- --pr=${{ env.PR_NUMBER }} --env=dev 

  deploy-on-test:

    name: Deploy TFRS on Test
    runs-on: ubuntu-latest
    timeout-minutes: 240
    needs: deploy-on-dev

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Openshift
        ##uses: redhat-actions/oc-login@v1
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools    

      - name: Ask for approval for TFRS Test deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,emi-hi,tim738745,vibhiquartech,kuanfandevops
          minimum-approvals: 1
          issue-title: "TFRS ${{ env.RELEASE_NAME }} Test Deployment"

      - name: Run deploy
        run: |
          cd .pipeline
          npm install
          npm run deploy -- --pr=${{ env.PR_NUMBER }} --env=test 

  deploy-on-prod:

    name: Deploy TFRS on Prod
    runs-on: ubuntu-latest
    timeout-minutes: 2880
    needs: deploy-on-test

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Openshift
        ##uses: redhat-actions/oc-login@v1
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools    

      - name: Ask for approval for TFRS Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,kuanfandevops,tim738745
          minimum-approvals: 3
          issue-title: "TFRS ${{ env.RELEASE_NAME }} Prod Deployment"

      - name: Run deploy
        run: |
          cd .pipeline
          echo "no prod deploy yet"
