## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: TFRS pipeline-2.0.0

on:
  push:
    branches: [ pipeline-2.0.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  ## Also remember to update the version in .pipeline/lib/config.js
  PR_NUMBER: 1825
  RELEASE_NAME: pipeline-2.0.0

jobs:

  ## This is the CI job
  build:

    name: Build TFRS on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v2

      ## Log in to Openshift with a token of service account
      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools

      ## Run build on Openshift
      - name: Run build
        run: |
          cd .pipeline
          npm install
          npm run build -- --pr=${{ env.PR_NUMBER }} --env=build 

  deploy-on-dev:

    name: Deploy TFRS on Dev
    runs-on: ubuntu-latest
    timeout-minutes: 240
    needs: build

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools    