## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: TFRS release-2.0.0

on:
  push:
    branches: [ release-2.0.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  ## Also remember to update the version in .pipeline/lib/config.js
  PR_NUMBER: 1824
  RELEASE_NAME: release-2.0.0

jobs:

  ## This is the CI job
  build:

    name: Build TFRS on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v2

      ## Log in to Openshift with a token of service account
      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools

