name: Scheduled cleanup old workflow runs
on:
  schedule:
    - cron: '0 0 * * 0'
# At 00:00 on Sunday.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 10