name: Create Release after merging to master
on:
  pull_request:
    types: [closed]
    branches:
      - 'master'     

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      releasename: ${{ github.event.pull_request.head.ref }}    
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${releasename/release-/v}
          tag_name: ${releasename/release-/v}
          body: |
            ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
