name: PR Teardown on Dev

on:
  pull_request:
    types: closed
    branches:
      - 'pr-build-jan'
      # - 'main-release-jan-2024'

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev

jobs:

  teardown-on-dev:
    if: endsWith( github.event.pull_request.title, 'build-on-dev' )
    name: Tear TFRS down on Dev
    runs-on: ubuntu-latest
    timeout-minutes: 20
 
    steps:

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}  

          # helm -n ${{ env.DEV_NAMESPACE }} uninstall tfrs-backend-dev-${{ github.event.pull_request.number }} || true
          # helm -n ${{ env.DEV_NAMESPACE }} uninstall tfrs-task-queue-dev-${{ github.event.pull_request.number }} || true
          # helm -n ${{ env.DEV_NAMESPACE }} uninstall tfrs-frontend-dev-${{ github.event.pull_request.number }} || true

      - name: Undeploy on Dev
        shell: bash {0}
        run: |
          helm -n ${{ env.DEV_NAMESPACE }} uninstall tfrs-spilo-jan-${{ github.event.pull_request.number }} || true
