{{- if .Values.route.createNotificationServerRoute }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tfrs-notification-server{{ .Values.suffix }}
  creationTimestamp:
  labels:
    {{- include "tfrs-notification-server.labels" . | nindent 4 }}
spec:
  host: tfrs{{ .Values.suffix }}.apps.silver.devops.gov.bc.ca
  path: /socket.io
  to:
    kind: Service
    name: tfrs-notification-server${SUFFIX}
    weight: 100
  port:
    targetPort: notification
  tls:
    termination: edge
  wildcardPolicy: None
status: {}
{{- end }}